# Do not edit this file!
# VUID ranges reserved for branches
# Key is branch name, value is [ start, end, nextfree ]
vuidCounts = {
    'branch-vuids': [ 4000, 4999, 4052 ],
    'devel': [ 3000, 3999, 3570 ],
    'master': [ 4000, 4999, 4052 ],
}
