name: 🐛 Bug report
description: Report something broken in the specification.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!

        Please remember that this GitHub repository is for the SYCL *specification*; if you have found a bug in a SYCL *implementation*, you should contact the developers of that implementation instead.

  - type: dropdown
    id: specification-version
    attributes:
      label: Specification Version
      description: |
        What version of the specification contains the bug?
      options:
        - SYCL 2020 (Revision 9)
        - SYCL 2020 (Source)
        - SYCL Next (Source)
      default: 0
    validations:
      required: true

  - type: textarea
    id: section-numbers
    attributes:
      label: Section Number(s)
      description: List out the section(s) containing the bug.
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: |
        Explain why the specification is wrong.
        Please be as detailed as possible, and quote the specification text.
    validations:
      required: true
