name: ❓ Clarification request
description: Highlight an inconsistency or unclear description.
labels: ["clarification"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to improve the SYCL specification.

  - type: dropdown
    id: specification-version
    attributes:
      label: Specification Version
      description: |
        What version of the specification is unclear?
      options:
        - SYCL 2020 (Revision 9)
        - SYCL 2020 (Source)
        - SYCL Next (Source)
      default: 0
    validations:
      required: true

  - type: textarea
    id: section-numbers
    attributes:
      label: Section Number(s)
      description: List out the section(s) that are unclear, including a link if you are viewing the HTML source (e.g., Section 5.6. Preprocessor directives and macros, https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_preprocessor_directives_and_macros).
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: |
        Explain why you think the specification is unclear.
        Please be as detailed as possible, and quote the specification text.
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example (Optional)
      description: |
        Provide one or more SYCL examples to demonstrate the issue.
        This is not required, but may help others to understand the issue.
    validations:
      required: false
