name: 🚀 Feature request
description: Request a new SYCL feature or extension.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to improve the SYCL specification.

  - type: dropdown
    id: extension-type
    attributes:
      label: Extension Type
      description: |
        Is this an improvement to an existing SYCL feature, or a brand new feature?
      options:
        - "Improvement"
        - "New Feature"
      default: 1
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: |
        Describe the desired feature in as much detail as possible.
        Be sure to explain why existing features are insufficient.
    validations:
      required: true

  - type: textarea
    id: cpp-features
    attributes:
      label: Related Functionality in C++
      description: |
        If related functionality already exists in C++, please provide
        details. 
    validations:
      required: false

  - type: textarea
    id: similar-features
    attributes:
      label: Related Functionality in Other Languages
      description: |
        If related functionality already exists in other languages (e.g.,
        OpenCL, CUDA, OpenMP), please provide details.
    validations:
      required: false

  - type: textarea
    id: existing-extensions
    attributes:
      label: Related SYCL Extensions
      description: |
        If related functionality already exists in the form of a SYCL
        extension, please provide a link to that extension.
    validations:
      required: false

