:dpcpp: pass:[DPC++]

[[sec:khr-properties]]
= sycl_khr_properties

This extension provides an alternative to the [code]#sycl::property_list# class,
the properties that are defined in the [code]#sycl::property# namespace, and the
APIs defined in <<sec:properties>>.
This new properties infrastructure provides all the same functionality, but also
provides a way to convey compile-time property information.
As a result, APIs that accept properties can detect errors at compilation time
(vs. runtime), and properties can be used to influence the code that the
compiler generates.

[[sec:khr-properties-dependencies]]
== Dependencies

This extension has no dependencies on other extensions.

[[sec:khr-properties-feature-test]]
== Feature test macro

An implementation supporting this extension must predefine the macro
[code]#SYCL_KHR_PROPERTIES# to one of the values defined in the table below.

[%header,cols="1,5"]
|===
|Value
|Description

|1
|Initial version of this extension.
|===

[[sec:khr-properties-overview]]
== Overview

This section illustrates the overall usage of the new property APIs introduced
by this extension.
The text in this section is non-normative, but it is intended to help readers
understand the formal specification that follows.

[[sec:khr-properties-overview-defining-properties]]
=== Defining and obtaining a property

There is no formal specification for a property because there is no facility to
allow an application to define their own properties.
Properties can only be defined by the SYCL implementation, so the SYCL
specification (or an extension specification) provides a formal specification
for each property.
Still, implementations are expected to follow a regular pattern when defining
properties.
This section describes the basics of that pattern, and more guidance is given
below in the examples in <<sec:khr-properties-examples-for-implementors>>.

A property can contain zero or more values.
Each value can either be a compile-time constant or a runtime-supplied value.
Any single property normally contains only compile-time constant values or
contains only runtime-supplied values, however, it is possible for a property to
contain a mixture of both value types.

A property with one or more runtime-supplied values is defined as a class with
constructors that set the property's values and public member variables that
hold the property's values.
An application obtains the property by constructing an instance of the class.

[source,,linenums]
----
namespace sycl::khr::property {

// Property defined by the implementation.
struct prop1 {
  constexpr prop1(int v) : value(v) {}
  int value;
};

}

// Application code that obtains the property.
sycl::khr::property::prop1 p1{42};
----

A property with one or more compile-time constant values is defined as a
variable template, where the template parameters set the property's values.
The variable's type is unspecified, but it is a class with static constexpr
member variables that hold the property's values.
An application obtains the property by instantiating the template.

[source,,linenums]
----
namespace sycl::khr::property {

// Property defined by the implementation.
template<int Value>
struct __unspecified_type__ {
  static constexpr int value = Value;
};

template<int Value>
inline constexpr __unspecified_type__<Value> prop2;

}

// Application code that obtains the property.
auto p2 = sycl::khr::property::prop2<42>;
----

A property with a mixture of runtime-supplied values and compile-time constant
values is defined as a class template.
The template parameters set the compile-time constant values, and the class
constructors set the runtime-supplied values.
An application obtains the property by constructing an instance of the class
template.

[source,,linenums]
----
namespace sycl::khr::property {

// Property defined by the implementation.
template<int Value1>
struct prop3 {
  constexpr prop1(int v2) : value2(v2) {}
  static constexpr int value1 = Value1;
  int value2;
};

}

// Application code that obtains the property.
auto p3 = sycl::khr::property::prop3<42>{43};
----

[[sec:khr-properties-overview-properties-lists]]
=== Properties lists

Applications often need to collect a set of properties into a container, for
example when constructing an object with more than one property.
This extension introduces a [code]#properties# class for this purpose, which
improves upon [code]#property_list# from the <<core-spec>>.
The [code]#properties# class is templated on the types of all the properties
that it contains.
This means that the template parameters also encode the compile-time constant
values for any properties it contains because those values are also part of
their property's type.

Applications can construct a [code]#properties# object from a list of
properties, and the template parameters are deduced through CTAD:

[source,,linenums]
----
sycl::khr::properties plist{
  sycl::khr::property::prop1{42},
  sycl::khr::property::prop2<42>,
  sycl::khr::property::prop3<42>{43}
};
----

Applications can also query whether a [code]#properties# list contains a certain
property, and they can get a copy of a property object from the list.
Each property defines an associated class in the [code]#property::key# namespace
for this purpose, and this class is known as the property's "key":

[source,,linenums]
----
if constexpr (plist.has_property<sycl::khr::property::key::prop2>()) {
  if constexpr (plist.get_property<sycl::khr::property::key::prop2>().value == 42) {
    /*...*/
  }
}
----

Notice above that we can use [code]#if constexpr# to query for the property's
existence because the type of [code]#plist# encodes the properties that it
contains.
When the property's value is a compile-time constant, we can also use [code]#if
constexpr# to get the value of the property because the type of [code]#plist#
also encodes the property's value.

Querying a property list for a property with runtime-supplied values is similar,
except that the call to [code]#get_property# returns a runtime value, so it is
not possible to use [code]#if constexpr# to test the property's value:

[source,,linenums]
----
if constexpr (plist.has_property<sycl::khr::property::key::prop1>()) {
  if (plist.get_property<sycl::khr::property::key::prop1>().value == 42) {
    /*...*/
  }
}
----

[[sec:khr-properties-properties]]
== The properties class

This extension adds the following new class, which holds a list of properties.

[source,role=synopsis,id=api:khr-properties-properties]
----
namespace sycl::khr {

template <typename... EncodedProperties>
class properties {
 public:
  template<typename... Properties>
  constexpr properties(Properties... props);

  template <typename PropertyKey>
  static constexpr bool has_property();

  template <typename PropertyKey>
  static constexpr auto get_property();

  template <typename PropertyKey>
  constexpr auto get_property();
};

using empty_properties_t = decltype(properties{});

} // namespace sycl::khr
----

{note}Implementations are expected to have a deduction guide that deduces
[code]#EncodedProperties# from the constructor's [code]#Properties# pack.
This deduction guide could trivially deduce [code]#EncodedProperties# as exactly
the same pack as [code]#Properties#.
However, in the future, this KHR extension might be extended in a way that
requires a more complex deduction.
Applications should not assume that [code]#EncodedProperties# is the same as
[code]#Properties#.
{endnote}

'''

.[apititle]#Constructor#
[source,role=synopsis,id=api:khr-properties-ctor]
----
template<typename... Properties>
constexpr properties(Properties... props);
----

_Constraints:_ [api]#khr::is_property_v# is [code]#true# for each
[code]#Properties#.

_Mandates:_ No two properties in [code]#Properties# have the same associated
key.

_Effects:_ Constructs a [code]#khr::properties# object from zero or more
properties.

'''

.[apidef]#khr::properties::has_property#
[source,role=synopsis,id=api:khr-properties-has-property]
----
template <typename PropertyKey>
static constexpr bool has_property();
----

_Constraints:_ [code]#khr::is_property_key_v<PropertyKey># is [code]#true#.

_Returns:_ The value [code]#true# only if this properties list contains a
property whose key is [code]#PropertyKey#.

'''

.[apidef]#khr::properties::get_property#
[source,role=synopsis,id=api:khr-properties-get-property]
----
template <typename PropertyKey>         (1)
static constexpr auto get_property();

template <typename PropertyKey>         (2)
constexpr auto get_property();
----

_Constraints_ (1):

* [code]#has_property<PropertyKey>()# is [code]#true#, and
* [code]#khr::is_property_key_compile_time_v<PropertyKey># is [code]#true#.

_Constraints_ (2):

* [code]#has_property<PropertyKey>()# is [code]#true#, and
* [code]#khr::is_property_key_compile_time_v<PropertyKey># is false.

_Returns:_ A copy of the property from this properties list whose associated key
is [code]#PropertyKey#.

'''

.[apidef]#khr::empty_properties_t#
[source,role=synopsis,id=api:khr-properties-empty-properties-t]
----
using empty_properties_t = decltype(properties{});
----

[code]#empty_properties_t# is the type of an empty properties list.

'''

[[sec:khr-properties-traits]]
== Property traits

This extension adds the following traits that classify properties, their keys,
and properties lists.

If the program adds specializations for any of the traits defined in this
section, the behavior is undefined.

'''

.[apidef]#khr::is_property#
[source,role=synopsis,id=api:khr-properties-is-property]
----
namespace sycl::khr {

template <typename T>
struct is_property;

template <typename T>
inline constexpr bool is_property_v = is_property<T>::value;

} // namespace sycl::khr
----

[code]#is_property# inherits from [code]#std::true_type# if [code]#T# is the
type of a new-style property that can be used in the APIs of this extension.
Otherwise it inherits from [code]#std::false_type#.

'''

.[apidef]#khr::is_property_key#
[source,role=synopsis,id=api:khr-properties-is-property-key]
----
namespace sycl::khr {

template <typename T>
struct is_property_key;

template <typename T>
inline constexpr bool is_property_key_v = is_property_key<T>::value;

} // namespace sycl::khr
----

[code]#is_property_key# inherits from [code]#std::true_type# if [code]#T# is the
type of a property key.
Otherwise it inherits from [code]#std::false_type#.

'''

.[apidef]#khr::is_property_key_compile_time#
[source,role=synopsis,id=api:khr-properties-is-property-key-compile-time]
----
namespace sycl::khr {

template <typename T>
struct is_property_key_compile_time;

template <typename T>
inline constexpr bool is_property_key_compile_time_v =
  is_property_key_compile_time<T>::value;

} // namespace sycl::khr
----

[code]#is_property_key_compile_time# inherits from [code]#std::true_type# if
[code]#T# is the type of a property key whose associated property contains no
values that are runtime-provided.
Otherwise it inherits from [code]#std::false_type#.

'''

.[apidef]#khr::is_property_for#
[source,role=synopsis,id=api:khr-properties-is-property-for]
----
namespace sycl::khr {

template <typename T, typename Class>
struct is_property_for;

template <typename T, typename Class>
inline constexpr bool is_property_for_v = is_property_for<T, Class>::value;

} // namespace sycl::khr
----

[code]#is_property_for# inherits from [code]#std::true_type# if [code]#T# is the
type of a property which can be used with class [code]#Class#.
Otherwise it inherits from [code]#std::false_type#.

{note}Each property defines which classes it can be used with.
When a property is used to construct a class, [code]#Class# is often the type of
that class.
When a property is used in another way, the specification which defines the
property normally defines a class which can be used for the [code]#Class#
parameter in this trait.
{endnote}

'''

.[apidef]#khr::is_property_key_for#
[source,role=synopsis,id=api:khr-properties-is-property-key-for]
----
namespace sycl::khr {

template <typename T, typename Class>
struct is_property_key_for;

template <typename T, typename Class>
inline constexpr bool is_property_key_for_v = is_property_key_for<T, Class>::value;

} // namespace sycl::khr
----

[code]#is_property_key_for# inherits from [code]#std::true_type# if [code]#T# is
the type of a property key whose associated property can be used with class
[code]#Class#.
Otherwise it inherits from [code]#std::false_type#.

'''

.[apidef]#khr::is_property_list_for#
[source,role=synopsis,id=api:khr-properties-is-property-list-for]
----
namespace sycl::khr {

template <typename T, typename Class>
struct is_property_list_for;

template <typename T, typename Class>
inline constexpr bool is_property_list_for_v = is_property_list_for<T, Class>::value;

} // namespace sycl::khr
----

[code]#is_property_list_for# inherits from [code]#std::true_type# if [code]#T#
is the type of a properties list and all of the properties that it contains can
be used with class [code]#Class#.
Otherwise it inherits from [code]#std::false_type#.
When [code]#T# is the empty properties list, this trait inherits from
[code]#std::true_type#.

'''

[[sec:khr-properties-context-additions]]
== Additions to the context class

[[sec:khr-properties-context-constructors]]
=== New context constructors

TODO

[[sec:khr-properties-queue-additions]]
== Additions and modifications to the queue class

[[sec:khr-properties-queue-constructors]]
=== New queue constructors

This extension adds the following new constructors to the [api]#queue# class,
which allow a queue to be constructed with the new style properties defined in
this extension.

'''

[source,role=synopsis,id=api:khr-properties-queue]
----
namespace sycl {

class queue {
  template <typename PropertyOrList = khr::empty_properties_t>
  explicit queue(PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  explicit queue(const async_handler& asyncHandler,
                 PropertyOrList props = {});

  template <typename DeviceSelector, typename PropertyOrList = khr::empty_properties_t>
  explicit queue(const DeviceSelector& deviceSelector,
                 PropertyOrList props = {});

  template <typename DeviceSelector, typename PropertyOrList = khr::empty_properties_t>
  explicit queue(const DeviceSelector& deviceSelector,
                 const async_handler& asyncHandler,
                 PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  explicit queue(const device& syclDevice, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  explicit queue(const device& syclDevice, const async_handler& asyncHandler,
                 PropertyOrList props = {});

  template <typename DeviceSelector, typename PropertyOrList = khr::empty_properties_t>
  explicit queue(const context& syclContext, const DeviceSelector& deviceSelector,
                 PropertyOrList props = {});

  template <typename DeviceSelector, typename PropertyOrList = khr::empty_properties_t>
  explicit queue(const context& syclContext, const DeviceSelector& deviceSelector,
                 const async_handler& asyncHandler,
                 PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  explicit queue(const context& syclContext, const device& syclDevice,
                 PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  explicit queue(const context& syclContext, const device& syclDevice,
                 const async_handler& asyncHandler,
                 PropertyOrList props = {});

  bool is_in_order() const;

  bool khr_is_profiling_enabled() const;

  // ...
};

} // namespace sycl
----

'''

.[apititle]#Default constructor#
[source,role=synopsis,id=api:khr-properties-queue-ctor]
----
template <typename PropertyOrList = khr::empty_properties_t>
explicit queue(PropertyOrList props = {});
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, queue># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, queue># is [code]#true#.

_Effects:_ The same effect as [code]#queue(propList)# except that the properties
are specified by [code]#props#.

'''

.[apititle]#Constructor with async handler#
[source,role=synopsis,id=api:khr-properties-queue-ctor-async-handler]
----
template <typename PropertyOrList = khr::empty_properties_t>
explicit queue(const async_handler& asyncHandler,
               PropertyOrList props = {});
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, queue># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, queue># is [code]#true#.

_Effects:_ The same effect as [code]#queue(asyncHandler, propList)# except that
the properties are specified by [code]#props#.

'''

.[apititle]#Constructor with device selector#
[source,role=synopsis,id=api:khr-properties-queue-ctor-selector]
----
template <typename DeviceSelector, typename PropertyOrList = khr::empty_properties_t>
explicit queue(const DeviceSelector& deviceSelector,
               PropertyOrList props = {});
----

_Constraints:_

* [code]#DeviceSelector# is a type that satisfies the requirements of a
  <<device-selector>> as defined in <<sec:device-selector>>, and either
** [api]#khr::is_property_for_v<PropertyOrList, queue># is [code]#true#, or
** [api]#khr::is_property_list_for_v<PropertyOrList, queue># is [code]#true#.

_Effects:_ The same effect as [code]#queue(deviceSelector, propList)# except
that the properties are specified by [code]#props#.

'''

.[apititle]#Constructor with device selector and async handler#
[source,role=synopsis,id=api:khr-properties-queue-ctor-selector-async-handler]
----
template <typename DeviceSelector, typename PropertyOrList = khr::empty_properties_t>
explicit queue(const DeviceSelector& deviceSelector,
               const async_handler& asyncHandler,
               PropertyOrList props = {});
----

_Constraints:_

* [code]#DeviceSelector# is a type that satisfies the requirements of a
  <<device-selector>> as defined in <<sec:device-selector>>, and either
** [api]#khr::is_property_for_v<PropertyOrList, queue># is [code]#true#, or
** [api]#khr::is_property_list_for_v<PropertyOrList, queue># is [code]#true#.

_Effects:_ The same effect as [code]#queue(deviceSelector, asyncHandler,
propList)# except that the properties are specified by [code]#props#.

'''

.[apititle]#Constructor with device#
[source,role=synopsis,id=api:khr-properties-queue-ctor-device]
----
template <typename PropertyOrList = khr::empty_properties_t>
explicit queue(const device& syclDevice, PropertyOrList props = {});
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, queue># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, queue># is [code]#true#.

_Effects:_ The same effect as [code]#queue(syclDevice, propList)# except that
the properties are specified by [code]#props#.

'''

.[apititle]#Constructor with device and async handler#
[source,role=synopsis,id=api:khr-properties-queue-ctor-device-async-handler]
----
template <typename PropertyOrList = khr::empty_properties_t>
explicit queue(const device& syclDevice, const async_handler& asyncHandler,
               PropertyOrList props = {});
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, queue># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, queue># is [code]#true#.

_Effects:_ The same effect as [code]#queue(syclDevice, asyncHandler, propList)#
except that the properties are specified by [code]#props#.

'''

.[apititle]#Constructor with context and device selector#
[source,role=synopsis,id=api:khr-properties-queue-ctor-context-selector]
----
template <typename DeviceSelector, typename PropertyOrList = khr::empty_properties_t>
explicit queue(const context& syclContext, const DeviceSelector& deviceSelector,
               PropertyOrList props = {});
----

_Constraints:_

* [code]#DeviceSelector# is a type that satisfies the requirements of a
  <<device-selector>> as defined in <<sec:device-selector>>, and either
** [api]#khr::is_property_for_v<PropertyOrList, queue># is [code]#true#, or
** [api]#khr::is_property_list_for_v<PropertyOrList, queue># is [code]#true#.

_Effects:_ The same effect as [code]#queue(syclContext, deviceSelector,
propList)# except that the properties are specified by [code]#props#.

'''

.[apititle]#Constructor with context, device selector, and async handler#
[source,role=synopsis,id=api:khr-properties-queue-ctor-context-selector-async-handler]
----
template <typename DeviceSelector, typename PropertyOrList = khr::empty_properties_t>
explicit queue(const context& syclContext, const DeviceSelector& deviceSelector,
               const async_handler& asyncHandler,
               PropertyOrList props = {});
----

_Constraints:_

* [code]#DeviceSelector# is a type that satisfies the requirements of a
  <<device-selector>> as defined in <<sec:device-selector>>, and either
** [api]#khr::is_property_for_v<PropertyOrList, queue># is [code]#true#, or
** [api]#khr::is_property_list_for_v<PropertyOrList, queue># is [code]#true#.

_Effects:_ The same effect as [code]#queue(syclContext, deviceSelector,
asyncHandler, propList)# except that the properties are specified by
[code]#props#.

'''

.[apititle]#Constructor with context and device#
[source,role=synopsis,id=api:khr-properties-queue-ctor-context-device]
----
template <typename PropertyOrList = khr::empty_properties_t>
explicit queue(const context& syclContext, const device& syclDevice,
               PropertyOrList props = {});
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, queue># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, queue># is [code]#true#.

_Effects:_ The same effect as [code]#queue(syclContext, syclDevice, propList)#
except that the properties are specified by [code]#props#.

'''

.[apititle]#Constructor with context, device, and async handler#
[source,role=synopsis,id=api:khr-properties-queue-ctor-context-device-async-handler]
----
template <typename PropertyOrList = khr::empty_properties_t>
explicit queue(const context& syclContext, const device& syclDevice,
               const async_handler& asyncHandler,
               PropertyOrList props = {});
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, queue># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, queue># is [code]#true#.

_Effects:_ The same effect as [code]#queue(syclContext, syclDevice,
asyncHandler, propList)# except that the properties are specified by
[code]#props#.

[[sec:khr-properties-queue-member-funcs]]
=== New and modified queue member functions

This extension adds a new member function and modifies an existing one.

'''

.[apititle]#queue::is_in_order#
[source,role=synopsis,id=api:khr-properties-queue-is-in-order]
----
bool is_in_order() const;
----

_Returns:_ [code]#true# only if this queue was constructed as an in-order queue.

'''

.[apidef]#queue::khr_is_profiling_enabled#
[source,role=synopsis,id=api:khr-properties-queue-is-profiling-enabled]
----
bool khr_is_profiling_enabled() const;
----

_Returns:_ [code]#true# only if this queue was constructed with profiling
enabled.

'''

[[sec:khr-properties-queue-properties]]
=== New queue properties

This extension adds the following new style properties that can be used with the
[code]#queue# class.

'''

.[apidef]#khr::enable_profiling#
[source,role=synopsis,id=api:khr-properties-enable-profiling]
----
namespace sycl::khr::property {

struct enable_profiling {
  constexpr enable_profiling(bool v = true) : value{v} {}
  bool value;
};

namespace key {
struct enable_profiling {};
}

} // namespace sycl::khr
----

When a queue is constructed with this property and the [code]#value# is
[code]#true#, the effect is the same as if the queue was constructed with
[api]#property::queue::enable_profiling#.
If the [code]#value# is [code]#false#, this property has no effect on the
constructed queue.

The following traits inherit from [code]#std::true#:

* [code]#is_property<property::enable_profiling>#
* [code]#is_property_key<property::key::enable_profiling>#
* [code]#is_property_for<property::enable_profiling, queue>#
* [code]#is_property_key_for<property::key::enable_profiling, queue>#

[code]#property::enable_profiling# and [code]#property::key::enable_profiling#
are trivially copyable.

'''

.[apidef]#khr::in_order#
[source,role=synopsis,id=api:khr-properties-in-order]
----
namespace sycl::khr::property {

struct in_order {
  constexpr in_order(bool v = true) : value{v} {}
  bool value;
};

namespace key {
struct in_order {};
}

} // namespace sycl::khr
----

When a queue is constructed with this property and the [code]#value# is
[code]#true#, the effect is the same as if the queue was constructed with
[api]#property::queue::in_order#.
If the [code]#value# is [code]#false#, this property has no effect on the
constructed queue.

The following traits inherit from [code]#std::true#:

* [code]#is_property<property::in_order>#
* [code]#is_property_key<property::key::in_order>#
* [code]#is_property_for<property::in_order, queue>#
* [code]#is_property_key_for<property::key::in_order, queue>#

[code]#property::in_order# and [code]#property::key::in_order# are trivially
copyable.

== Additions to the buffer and image classes

[[sec:khr-properties-buffer-constructors]]
=== New buffer constructors

This extension adds the following new constructors to the [code]#buffer# class,
which allow a buffer to be constructed with the new style properties defined in
this extension.

'''

[source,role=synopsis,id=api:khr-properties-buffer]
----
namespace sycl {

template <typename T, int Dimensions, typename AllocatorT>
class buffer {
  template <typename PropertyOrList = khr::empty_properties_t>
  buffer(const range<Dimensions>& bufferRange, AllocatorT allocator,
         PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  buffer(const range<Dimensions>& bufferRange, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  buffer(T* hostData, const range<Dimensions>& bufferRange,
         AllocatorT allocator, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  buffer(T* hostData, const range<Dimensions>& bufferRange,
         PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  buffer(const T* hostData, const range<Dimensions>& bufferRange,
         AllocatorT allocator, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  buffer(const T* hostData, const range<Dimensions>& bufferRange,
         PropertyOrList props = {});

  template <typename Container, typename PropertyOrList = khr::empty_properties_t>
  buffer(Container& container, AllocatorT allocator, PropertyOrList props = {});

  template <typename Container, typename PropertyOrList = khr::empty_properties_t>
  buffer(Container& container, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  buffer(const std::shared_ptr<T>& hostData,
         const range<Dimensions>& bufferRange, AllocatorT allocator,
         PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  buffer(const std::shared_ptr<T>& hostData,
         const range<Dimensions>& bufferRange, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  buffer(const std::shared_ptr<T[]>& hostData,
         const range<Dimensions>& bufferRange, AllocatorT allocator,
         PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  buffer(const std::shared_ptr<T[]>& hostData,
         const range<Dimensions>& bufferRange, PropertyOrList props = {});

  template <typename InputIterator,
            typename PropertyOrList = khr::empty_properties_t>
  buffer(InputIterator first, InputIterator last, AllocatorT allocator,
         PropertyOrList props = {});

  template <typename InputIterator,
            typename PropertyOrList = khr::empty_properties_t>
  buffer(InputIterator first, InputIterator last, PropertyOrList props = {});

  // ...
};

} // namespace sycl
----

TODO: Do we need deduction guides?

'''

.[apititle]#Construct with uninitialized memory#
[source,role=synopsis,id=api:khr-properties-buffer-ctor-uninit]
----
template <typename PropertyOrList = khr::empty_properties_t>
buffer(const range<Dimensions>& bufferRange, AllocatorT allocator,  (1)
       PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
buffer(const range<Dimensions>& bufferRange, PropertyOrList props = {});  (2)
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, buffer># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, buffer># is [code]#true#.

_Effects (1):_ The same effect as [code]#buffer(bufferRange, allocator,
propList)# except that the properties are specified by [code]#props#.

_Effects (2):_ The same effect as [code]#buffer(bufferRange, propList)# except
that the properties are specified by [code]#props#.

'''

.[apititle]#Construct with host memory#
[source,role=synopsis,id=api:khr-properties-buffer-ctor-host-mem]
----
template <typename PropertyOrList = khr::empty_properties_t>
buffer(T* hostData, const range<Dimensions>& bufferRange,          (1)
       AllocatorT allocator, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
buffer(T* hostData, const range<Dimensions>& bufferRange,          (2)
       PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
buffer(const T* hostData, const range<Dimensions>& bufferRange,    (3)
       AllocatorT allocator, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
buffer(const T* hostData, const range<Dimensions>& bufferRange,    (4)
       PropertyOrList props = {});
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, buffer># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, buffer># is [code]#true#.

_Effects (1):_ The same effect as [code]#buffer(hostData, bufferRange,
allocator, propList)# except that the properties are specified by
[code]#props#.

_Effects (2):_ The same effect as [code]#buffer(hostData, bufferRange,
propList)# except that the properties are specified by [code]#props#.

_Effects (3):_ The same effect as [code]#buffer(hostData, bufferRange,
allocator, propList)# (the [code]#const T*# overload) except that the
properties are specified by [code]#props#.

_Effects (4):_ The same effect as [code]#buffer(hostData, bufferRange,
propList)# (the [code]#const T*# overload) except that the properties are
specified by [code]#props#.

'''

.[apititle]#Construct from a container#
[source,role=synopsis,id=api:khr-properties-buffer-ctor-container]
----
template <typename Container, typename PropertyOrList = khr::empty_properties_t>
buffer(Container& container, AllocatorT allocator,                 (1)
       PropertyOrList props = {});

template <typename Container, typename PropertyOrList = khr::empty_properties_t>
buffer(Container& container, PropertyOrList props = {});           (2)
----

_Constraints:_ The same constraints as the corresponding [code]#buffer#
container constructor from the <<core-spec>>, and either

* [api]#khr::is_property_for_v<PropertyOrList, buffer># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, buffer># is [code]#true#.

_Effects (1):_ The same effect as [code]#buffer(container, allocator,
propList)# except that the properties are specified by [code]#props#.

_Effects (2):_ The same effect as [code]#buffer(container, propList)# except
that the properties are specified by [code]#props#.

'''

.[apititle]#Construct from memory owned by a shared pointer#
[source,role=synopsis,id=api:khr-properties-buffer-ctor-shared-ptr]
----
template <typename PropertyOrList = khr::empty_properties_t>
buffer(const std::shared_ptr<T>& hostData,                         (1)
       const range<Dimensions>& bufferRange, AllocatorT allocator,
       PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
buffer(const std::shared_ptr<T>& hostData,                         (2)
       const range<Dimensions>& bufferRange, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
buffer(const std::shared_ptr<T[]>& hostData,                       (3)
       const range<Dimensions>& bufferRange, AllocatorT allocator,
       PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
buffer(const std::shared_ptr<T[]>& hostData,                       (4)
       const range<Dimensions>& bufferRange, PropertyOrList props = {});
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, buffer># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, buffer># is [code]#true#.

_Effects (1):_ The same effect as [code]#buffer(hostData, bufferRange,
allocator, propList)# (the [code]#shared_ptr<T># overload) except that the
properties are specified by [code]#props#.

_Effects (2):_ The same effect as [code]#buffer(hostData, bufferRange,
propList)# (the [code]#shared_ptr<T># overload) except that the properties are
specified by [code]#props#.

_Effects (3):_ The same effect as [code]#buffer(hostData, bufferRange,
allocator, propList)# (the [code]#shared_ptr<T[]># overload) except that the
properties are specified by [code]#props#.

_Effects (4):_ The same effect as [code]#buffer(hostData, bufferRange,
propList)# (the [code]#shared_ptr<T[]># overload) except that the properties
are specified by [code]#props#.

'''

.[apititle]#Construct from iterators#
[source,role=synopsis,id=api:khr-properties-buffer-ctor-iterator]
----
template <typename InputIterator,
          typename PropertyOrList = khr::empty_properties_t>
buffer(InputIterator first, InputIterator last, AllocatorT allocator,  (1)
       PropertyOrList props = {});

template <typename InputIterator,
          typename PropertyOrList = khr::empty_properties_t>
buffer(InputIterator first, InputIterator last, PropertyOrList props = {});  (2)
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, buffer># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, buffer># is [code]#true#.

_Effects (1):_ The same effect as [code]#buffer(first, last, allocator,
propList)# except that the properties are specified by [code]#props#.

_Effects (2):_ The same effect as [code]#buffer(first, last, propList)# except
that the properties are specified by [code]#props#.

[[sec:khr-properties-unsampled-image-constructors]]
=== New unsampled image constructors

This extension adds the following new constructors to the [code]#unsampled_image#
class, which allow an unsampled image to be constructed with the new style
properties defined in this extension.

'''

[source,role=synopsis,id=api:khr-properties-unsampled-image]
----
namespace sycl {

template <int Dimensions = 1, typename AllocatorT = image_allocator>
class unsampled_image {
  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(image_format format, const range<Dimensions>& rangeRef,
                  PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(image_format format, const range<Dimensions>& rangeRef,
                  AllocatorT allocator, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(image_format format, const range<Dimensions>& rangeRef,
                  const range<Dimensions - 1>& pitch, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(image_format format, const range<Dimensions>& rangeRef,
                  const range<Dimensions - 1>& pitch, AllocatorT allocator,
                  PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(void* hostPointer, image_format format,
                  const range<Dimensions>& rangeRef, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(void* hostPointer, image_format format,
                  const range<Dimensions>& rangeRef, AllocatorT allocator,
                  PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(void* hostPointer, image_format format,
                  const range<Dimensions>& rangeRef,
                  const range<Dimensions - 1>& pitch, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(void* hostPointer, image_format format,
                  const range<Dimensions>& rangeRef,
                  const range<Dimensions - 1>& pitch, AllocatorT allocator,
                  PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(std::shared_ptr<void>& hostPointer, image_format format,
                  const range<Dimensions>& rangeRef, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(std::shared_ptr<void>& hostPointer, image_format format,
                  const range<Dimensions>& rangeRef, AllocatorT allocator,
                  PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(std::shared_ptr<void>& hostPointer, image_format format,
                  const range<Dimensions>& rangeRef,
                  const range<Dimensions - 1>& pitch, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  unsampled_image(std::shared_ptr<void>& hostPointer, image_format format,
                  const range<Dimensions>& rangeRef,
                  const range<Dimensions - 1>& pitch, AllocatorT allocator,
                  PropertyOrList props = {});

  // ...
};

} // namespace sycl
----

'''

.[apititle]#Construct with uninitialized memory#
[source,role=synopsis,id=api:khr-properties-unsampled-image-ctor-uninit]
----
template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(image_format format, const range<Dimensions>& rangeRef,  (1)
                PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(image_format format, const range<Dimensions>& rangeRef,  (2)
                AllocatorT allocator, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(image_format format, const range<Dimensions>& rangeRef,  (3)
                const range<Dimensions - 1>& pitch, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(image_format format, const range<Dimensions>& rangeRef,  (4)
                const range<Dimensions - 1>& pitch, AllocatorT allocator,
                PropertyOrList props = {});
----

_Constraints:_ Overloads (3) and (4) are available only when
[code]#Dimensions > 1#, and for all overloads either

* [api]#khr::is_property_for_v<PropertyOrList, unsampled_image># is [code]#true#,
  or
* [api]#khr::is_property_list_for_v<PropertyOrList, unsampled_image># is
  [code]#true#.

_Effects (1)-(4):_ The same effect as the corresponding [code]#unsampled_image#
constructor with uninitialized memory from the <<core-spec>> except that the
properties are specified by [code]#props#.

'''

.[apititle]#Construct with host memory#
[source,role=synopsis,id=api:khr-properties-unsampled-image-ctor-host-mem]
----
template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(void* hostPointer, image_format format,                  (1)
                const range<Dimensions>& rangeRef, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(void* hostPointer, image_format format,                  (2)
                const range<Dimensions>& rangeRef, AllocatorT allocator,
                PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(void* hostPointer, image_format format,                  (3)
                const range<Dimensions>& rangeRef,
                const range<Dimensions - 1>& pitch, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(void* hostPointer, image_format format,                  (4)
                const range<Dimensions>& rangeRef,
                const range<Dimensions - 1>& pitch, AllocatorT allocator,
                PropertyOrList props = {});
----

_Constraints:_ Overloads (3) and (4) are available only when
[code]#Dimensions > 1#, and for all overloads either

* [api]#khr::is_property_for_v<PropertyOrList, unsampled_image># is [code]#true#,
  or
* [api]#khr::is_property_list_for_v<PropertyOrList, unsampled_image># is
  [code]#true#.

_Effects (1)-(4):_ The same effect as the corresponding [code]#unsampled_image#
constructor with host memory from the <<core-spec>> except that the properties
are specified by [code]#props#.

'''

.[apititle]#Construct from memory owned by a shared pointer#
[source,role=synopsis,id=api:khr-properties-unsampled-image-ctor-shared-ptr]
----
template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(std::shared_ptr<void>& hostPointer, image_format format,  (1)
                const range<Dimensions>& rangeRef, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(std::shared_ptr<void>& hostPointer, image_format format,  (2)
                const range<Dimensions>& rangeRef, AllocatorT allocator,
                PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(std::shared_ptr<void>& hostPointer, image_format format,  (3)
                const range<Dimensions>& rangeRef,
                const range<Dimensions - 1>& pitch, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
unsampled_image(std::shared_ptr<void>& hostPointer, image_format format,  (4)
                const range<Dimensions>& rangeRef,
                const range<Dimensions - 1>& pitch, AllocatorT allocator,
                PropertyOrList props = {});
----

_Constraints:_ Overloads (3) and (4) are available only when
[code]#Dimensions > 1#, and for all overloads either

* [api]#khr::is_property_for_v<PropertyOrList, unsampled_image># is [code]#true#,
  or
* [api]#khr::is_property_list_for_v<PropertyOrList, unsampled_image># is
  [code]#true#.

_Effects (1)-(4):_ The same effect as the corresponding [code]#unsampled_image#
constructor from memory owned by a shared pointer from the <<core-spec>> except
that the properties are specified by [code]#props#.

[[sec:khr-properties-sampled-image-constructors]]
=== New sampled image constructors

This extension adds the following new constructors to the [code]#sampled_image#
class, which allow a sampled image to be constructed with the new style
properties defined in this extension.

'''

[source,role=synopsis,id=api:khr-properties-sampled-image]
----
namespace sycl {

template <int Dimensions = 1, typename AllocatorT = image_allocator>
class sampled_image {
  template <typename PropertyOrList = khr::empty_properties_t>
  sampled_image(const void* hostPointer, image_format format,
                image_sampler sampler, const range<Dimensions>& rangeRef,
                PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  sampled_image(const void* hostPointer, image_format format,
                image_sampler sampler, const range<Dimensions>& rangeRef,
                AllocatorT allocator, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  sampled_image(const void* hostPointer, image_format format,
                image_sampler sampler, const range<Dimensions>& rangeRef,
                const range<Dimensions - 1>& pitch, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  sampled_image(const void* hostPointer, image_format format,
                image_sampler sampler, const range<Dimensions>& rangeRef,
                const range<Dimensions - 1>& pitch, AllocatorT allocator,
                PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  sampled_image(std::shared_ptr<const void>& hostPointer, image_format format,
                image_sampler sampler, const range<Dimensions>& rangeRef,
                PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  sampled_image(std::shared_ptr<const void>& hostPointer, image_format format,
                image_sampler sampler, const range<Dimensions>& rangeRef,
                AllocatorT allocator, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  sampled_image(std::shared_ptr<const void>& hostPointer, image_format format,
                image_sampler sampler, const range<Dimensions>& rangeRef,
                const range<Dimensions - 1>& pitch, PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  sampled_image(std::shared_ptr<const void>& hostPointer, image_format format,
                image_sampler sampler, const range<Dimensions>& rangeRef,
                const range<Dimensions - 1>& pitch, AllocatorT allocator,
                PropertyOrList props = {});

  // ...
};

} // namespace sycl
----

'''

.[apititle]#Construct with host memory#
[source,role=synopsis,id=api:khr-properties-sampled-image-ctor-host-mem]
----
template <typename PropertyOrList = khr::empty_properties_t>
sampled_image(const void* hostPointer, image_format format,              (1)
              image_sampler sampler, const range<Dimensions>& rangeRef,
              PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
sampled_image(const void* hostPointer, image_format format,              (2)
              image_sampler sampler, const range<Dimensions>& rangeRef,
              AllocatorT allocator, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
sampled_image(const void* hostPointer, image_format format,              (3)
              image_sampler sampler, const range<Dimensions>& rangeRef,
              const range<Dimensions - 1>& pitch, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
sampled_image(const void* hostPointer, image_format format,              (4)
              image_sampler sampler, const range<Dimensions>& rangeRef,
              const range<Dimensions - 1>& pitch, AllocatorT allocator,
              PropertyOrList props = {});
----

_Constraints:_ Overloads (3) and (4) are available only when
[code]#Dimensions > 1#, and for all overloads either

* [api]#khr::is_property_for_v<PropertyOrList, sampled_image># is [code]#true#,
  or
* [api]#khr::is_property_list_for_v<PropertyOrList, sampled_image># is
  [code]#true#.

_Effects (1)-(4):_ The same effect as the corresponding [code]#sampled_image#
constructor with host memory from the <<core-spec>> except that the properties
are specified by [code]#props#.

'''

.[apititle]#Construct from memory owned by a shared pointer#
[source,role=synopsis,id=api:khr-properties-sampled-image-ctor-shared-ptr]
----
template <typename PropertyOrList = khr::empty_properties_t>
sampled_image(std::shared_ptr<const void>& hostPointer,                  (1)
              image_format format, image_sampler sampler,
              const range<Dimensions>& rangeRef, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
sampled_image(std::shared_ptr<const void>& hostPointer,                  (2)
              image_format format, image_sampler sampler,
              const range<Dimensions>& rangeRef, AllocatorT allocator,
              PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
sampled_image(std::shared_ptr<const void>& hostPointer,                  (3)
              image_format format, image_sampler sampler,
              const range<Dimensions>& rangeRef,
              const range<Dimensions - 1>& pitch, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
sampled_image(std::shared_ptr<const void>& hostPointer,                  (4)
              image_format format, image_sampler sampler,
              const range<Dimensions>& rangeRef,
              const range<Dimensions - 1>& pitch, AllocatorT allocator,
              PropertyOrList props = {});
----

_Constraints:_ Overloads (3) and (4) are available only when
[code]#Dimensions > 1#, and for all overloads either

* [api]#khr::is_property_for_v<PropertyOrList, sampled_image># is [code]#true#,
  or
* [api]#khr::is_property_list_for_v<PropertyOrList, sampled_image># is
  [code]#true#.

_Effects (1)-(4):_ The same effect as the corresponding [code]#sampled_image#
constructor from memory owned by a shared pointer from the <<core-spec>> except
that the properties are specified by [code]#props#.

[[sec:khr-properties-buffer-image-properties]]
=== New buffer and image properties

This extension adds the following new style properties that can be used with the
[code]#buffer#, [code]#unsampled_image#, and [code]#sampled_image# classes.
These properties provide the same functionality as the corresponding
[code]#property::buffer# and [code]#property::image# properties from the
<<core-spec>>.

'''

.[apidef]#khr::use_host_ptr#
[source,role=synopsis,id=api:khr-properties-use-host-ptr]
----
namespace sycl::khr::property {

struct use_host_ptr {
  constexpr use_host_ptr(bool v = true) : value{v} {}
  bool value;
};

namespace key {
struct use_host_ptr {};
}

} // namespace sycl::khr
----

When a buffer or image is constructed with this property and the [code]#value#
is [code]#true#, the effect is the same as if it was constructed with
[api]#property::buffer::use_host_ptr# (for a [code]#buffer#) or
[code]#property::image::use_host_ptr# (for an [code]#unsampled_image# or
[code]#sampled_image#).
If the [code]#value# is [code]#false#, this property has no effect on the
constructed object.

The following traits inherit from [code]#std::true#:

* [code]#is_property<property::use_host_ptr>#
* [code]#is_property_key<property::key::use_host_ptr>#
* [code]#is_property_for<property::use_host_ptr, buffer>#
* [code]#is_property_for<property::use_host_ptr, unsampled_image>#
* [code]#is_property_for<property::use_host_ptr, sampled_image>#
* [code]#is_property_key_for<property::key::use_host_ptr, buffer>#
* [code]#is_property_key_for<property::key::use_host_ptr, unsampled_image>#
* [code]#is_property_key_for<property::key::use_host_ptr, sampled_image>#

[code]#property::use_host_ptr# and [code]#property::key::use_host_ptr# are
trivially copyable.

'''

.[apidef]#khr::use_mutex#
[source,role=synopsis,id=api:khr-properties-use-mutex]
----
namespace sycl::khr::property {

struct use_mutex {
  use_mutex(std::mutex& mutexRef);
  std::mutex* get_mutex_ptr() const;
};

namespace key {
struct use_mutex {};
}

} // namespace sycl::khr
----

The [code]#use_mutex# property adds the requirement that the memory owned by the
[code]#buffer# or image can be shared with the application via the
[code]#std::mutex# provided to the property, with the same effect as
[api]#property::buffer::use_mutex# (for a [code]#buffer#) or
[code]#property::image::use_mutex# (for an [code]#unsampled_image# or
[code]#sampled_image#).

[code]#get_mutex_ptr# returns a pointer to the [code]#std::mutex# provided when
constructing this property.

The following traits inherit from [code]#std::true#:

* [code]#is_property<property::use_mutex>#
* [code]#is_property_key<property::key::use_mutex>#
* [code]#is_property_for<property::use_mutex, buffer>#
* [code]#is_property_for<property::use_mutex, unsampled_image>#
* [code]#is_property_for<property::use_mutex, sampled_image>#
* [code]#is_property_key_for<property::key::use_mutex, buffer>#
* [code]#is_property_key_for<property::key::use_mutex, unsampled_image>#
* [code]#is_property_key_for<property::key::use_mutex, sampled_image>#

'''

.[apidef]#khr::context_bound#
[source,role=synopsis,id=api:khr-properties-context-bound]
----
namespace sycl::khr::property {

struct context_bound {
  context_bound(context boundContext);
  context get_context() const;
};

namespace key {
struct context_bound {};
}

} // namespace sycl::khr
----

The [code]#context_bound# property adds the requirement that the [code]#buffer#
or image can only be associated with the single [code]#context# provided to the
property, with the same effect as [api]#property::buffer::context_bound# (for a
[code]#buffer#) or [code]#property::image::context_bound# (for an
[code]#unsampled_image# or [code]#sampled_image#).

[code]#get_context# returns the [code]#context# provided when constructing this
property.

The following traits inherit from [code]#std::true#:

* [code]#is_property<property::context_bound>#
* [code]#is_property_key<property::key::context_bound>#
* [code]#is_property_for<property::context_bound, buffer>#
* [code]#is_property_for<property::context_bound, unsampled_image>#
* [code]#is_property_for<property::context_bound, sampled_image>#
* [code]#is_property_key_for<property::key::context_bound, buffer>#
* [code]#is_property_key_for<property::key::context_bound, unsampled_image>#
* [code]#is_property_key_for<property::key::context_bound, sampled_image>#

== Additions to the accessor classes

// Intentionally empty: this extension does not currently add new-style property
// support to the accessor classes. See the corresponding bullet in the Issues
// section on whether the accessor API should be extended given that no property
// is presently used with accessors.

=== New buffer accessor constructors

=== New buffer host accessor constructors

=== New local accessor constructors

=== New unsampled image accessor constructors

=== New unsampled image host accessor constructors

=== New sampled image accessor constructors

=== New sampled image host accessor constructors

=== New accessor properties

[[sec:khr-properties-usm-additions]]
== Additions to the USM functions

This extension adds new property-accepting overloads to the [code]#usm_allocator#
constructors and to the USM allocation functions.

Most of the USM allocation entry points are free functions, which are not classes,
so this extension defines an empty tag type [code]#khr::usm_allocation# to serve as
the [code]#Class# parameter of the [api]#khr::is_property_for# trait for properties
that can be used with the USM allocator and the USM allocation functions.

'''

[source,role=synopsis,id=api:khr-properties-usm-allocation-tag]
----
namespace sycl::khr {

struct usm_allocation; // tag type, never defined

} // namespace sycl::khr
----

[[sec:khr-properties-usm-allocator-constructors]]
=== New USM allocator constructors

This extension adds the following new constructors to the [code]#usm_allocator#
class, which allow an allocator to be constructed with the new style properties
defined in this extension.

'''

[source,role=synopsis,id=api:khr-properties-usm-allocator]
----
namespace sycl {

template <typename T, usm::alloc AllocKind, std::size_t Alignment = 0>
class usm_allocator {
  template <typename PropertyOrList = khr::empty_properties_t>
  usm_allocator(const context& syclContext, const device& syclDevice,  // (1)
                PropertyOrList props = {});

  template <typename PropertyOrList = khr::empty_properties_t>
  usm_allocator(const queue& syclQueue, PropertyOrList props = {});     // (2)

  // ...
};

} // namespace sycl
----

_Constraints:_ For both overloads, either

* [api]#khr::is_property_for_v<PropertyOrList, usm_allocation># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, usm_allocation># is
  [code]#true#.

_Effects (1)-(2):_ The same effect as the corresponding [code]#usm_allocator#
constructor from the <<core-spec>> except that the properties are specified by
[code]#props#.

[[sec:khr-properties-usm-device-allocs]]
=== New device allocation functions

This extension adds the following new overloads of the device USM allocation
functions.

TODO: Missing overloads with "count"

'''

[source,role=synopsis,id=api:khr-properties-usm-malloc-device]
----
namespace sycl {

template <typename PropertyOrList = khr::empty_properties_t>
void* malloc_device(std::size_t numBytes, const device& syclDevice,       // (1)
                    const context& syclContext, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* malloc_device(std::size_t numBytes, const queue& syclQueue,         // (2)
                    PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* aligned_alloc_device(std::size_t alignment, std::size_t numBytes,   // (3)
                           const device& syclDevice, const context& syclContext,
                           PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* aligned_alloc_device(std::size_t alignment, std::size_t numBytes,   // (4)
                           const queue& syclQueue, PropertyOrList props = {});

} // namespace sycl
----

_Constraints:_ For all overloads, either

* [api]#khr::is_property_for_v<PropertyOrList, usm_allocation># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, usm_allocation># is
  [code]#true#.

_Effects (1)-(4):_ The same effect as the corresponding device USM allocation
function from the <<core-spec>> except that the properties are specified by
[code]#props#.

[[sec:khr-properties-usm-host-allocs]]
=== New host allocation functions

This extension adds the following new overloads of the host USM allocation
functions.

TODO: Missing overloads with "count"

'''

[source,role=synopsis,id=api:khr-properties-usm-malloc-host]
----
namespace sycl {

template <typename PropertyOrList = khr::empty_properties_t>
void* malloc_host(std::size_t numBytes, const context& syclContext,       // (1)
                  PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* malloc_host(std::size_t numBytes, const queue& syclQueue,           // (2)
                  PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* aligned_alloc_host(std::size_t alignment, std::size_t numBytes,     // (3)
                         const context& syclContext, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* aligned_alloc_host(std::size_t alignment, std::size_t numBytes,     // (4)
                         const queue& syclQueue, PropertyOrList props = {});

} // namespace sycl
----

_Constraints:_ For all overloads, either

* [api]#khr::is_property_for_v<PropertyOrList, usm_allocation># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, usm_allocation># is
  [code]#true#.

_Effects (1)-(4):_ The same effect as the corresponding host USM allocation
function from the <<core-spec>> except that the properties are specified by
[code]#props#.

[[sec:khr-properties-usm-shared-allocs]]
=== New shared allocation functions

This extension adds the following new overloads of the shared USM allocation
functions.

TODO: Missing overloads with "count"

'''

[source,role=synopsis,id=api:khr-properties-usm-malloc-shared]
----
namespace sycl {

template <typename PropertyOrList = khr::empty_properties_t>
void* malloc_shared(std::size_t numBytes, const device& syclDevice,       // (1)
                    const context& syclContext, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* malloc_shared(std::size_t numBytes, const queue& syclQueue,         // (2)
                    PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* aligned_alloc_shared(std::size_t alignment, std::size_t numBytes,   // (3)
                           const device& syclDevice, const context& syclContext,
                           PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* aligned_alloc_shared(std::size_t alignment, std::size_t numBytes,   // (4)
                           const queue& syclQueue, PropertyOrList props = {});

} // namespace sycl
----

_Constraints:_ For all overloads, either

* [api]#khr::is_property_for_v<PropertyOrList, usm_allocation># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, usm_allocation># is
  [code]#true#.

_Effects (1)-(4):_ The same effect as the corresponding shared USM allocation
function from the <<core-spec>> except that the properties are specified by
[code]#props#.

[[sec:khr-properties-usm-parameterized-allocs]]
=== New parameterized allocation functions

This extension adds the following new overloads of the parameterized USM
allocation functions, which select the kind of allocation through a
[code]#usm::alloc# parameter.

TODO: Missing overloads with "count"

'''

[source,role=synopsis,id=api:khr-properties-usm-malloc]
----
namespace sycl {

template <typename PropertyOrList = khr::empty_properties_t>
void* malloc(std::size_t numBytes, const device& syclDevice,             // (1)
             const context& syclContext, usm::alloc kind,
             PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* malloc(std::size_t numBytes, const queue& syclQueue, usm::alloc kind, // (2)
             PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* aligned_alloc(std::size_t alignment, std::size_t numBytes,         // (3)
                    const device& syclDevice, const context& syclContext,
                    usm::alloc kind, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
void* aligned_alloc(std::size_t alignment, std::size_t numBytes,         // (4)
                    const queue& syclQueue, usm::alloc kind,
                    PropertyOrList props = {});

} // namespace sycl
----

_Constraints:_ For all overloads, either

* [api]#khr::is_property_for_v<PropertyOrList, usm_allocation># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, usm_allocation># is
  [code]#true#.

_Effects (1)-(4):_ The same effect as the corresponding parameterized USM
allocation function from the <<core-spec>> except that the properties are
specified by [code]#props#.

[[sec:khr-properties-usm-properties]]
=== New USM properties

This extension defines no USM property.
The overloads above are added so that a future USM property (defined by the
<<core-spec>> or by another extension) can be passed through the new style
[code]#properties# mechanism.

== Additions to the reduction interface

[[sec:khr-properties-reduction-overloads]]
=== New reduction function overloads

This extension adds the following new overloads to the [code]#reduction#
interface, which allow a reduction to be created with the new style properties
defined in this extension.

The [code]#reduction# interface is not a class, so this extension defines an
empty tag type [code]#khr::reduction# to serve as the [code]#Class# parameter of
the [api]#khr::is_property_for# trait for properties that can be used with the
[code]#reduction# interface.

'''

[source,role=synopsis,id=api:khr-properties-reduction-tag]
----
namespace sycl::khr {

struct reduction; // tag type, never defined

} // namespace sycl::khr
----

'''

[source,role=synopsis,id=api:khr-properties-reduction]
----
namespace sycl {

template <typename BufferT, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(BufferT vars, handler& cgh, BinaryOperation combiner,
                          PropertyOrList props = {});

template <typename T, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(T* var, BinaryOperation combiner,
                          PropertyOrList props = {});

template <typename T, typename Extent, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(span<T, Extent> vars, BinaryOperation combiner,
                          PropertyOrList props = {});

template <typename BufferT, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(BufferT vars, handler& cgh,
                          const BufferT::value_type& identity,
                          BinaryOperation combiner, PropertyOrList props = {});

template <typename T, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(T* var, const T& identity, BinaryOperation combiner,
                          PropertyOrList props = {});

template <typename T, typename Extent, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(span<T, Extent> vars, const T& identity,
                          BinaryOperation combiner, PropertyOrList props = {});

} // namespace sycl
----

'''

.[apititle]#Reduction without an identity value#
[source,role=synopsis,id=api:khr-properties-reduction-no-identity]
----
template <typename BufferT, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(BufferT vars, handler& cgh,              (1)
                          BinaryOperation combiner, PropertyOrList props = {});

template <typename T, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(T* var, BinaryOperation combiner,        (2)
                          PropertyOrList props = {});

template <typename T, typename Extent, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(span<T, Extent> vars,                    (3)
                          BinaryOperation combiner, PropertyOrList props = {});
----

_Constraints:_ Overload (3) is available only when
[code]#Extent != sycl::dynamic_extent#, and for all overloads either

* [api]#khr::is_property_for_v<PropertyOrList, reduction># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, reduction># is [code]#true#.

_Effects (1)-(3):_ The same effect as the corresponding [code]#reduction#
overload without an identity value from the <<core-spec>> except that the
properties are specified by [code]#props#.

'''

.[apititle]#Reduction with an identity value#
[source,role=synopsis,id=api:khr-properties-reduction-identity]
----
template <typename BufferT, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(BufferT vars, handler& cgh,             (1)
                          const BufferT::value_type& identity,
                          BinaryOperation combiner, PropertyOrList props = {});

template <typename T, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(T* var, const T& identity,             (2)
                          BinaryOperation combiner, PropertyOrList props = {});

template <typename T, typename Extent, typename BinaryOperation,
          typename PropertyOrList = khr::empty_properties_t>
__unspecified__ reduction(span<T, Extent> vars, const T& identity,  (3)
                          BinaryOperation combiner, PropertyOrList props = {});
----

_Constraints:_ Overload (3) is available only when
[code]#Extent != sycl::dynamic_extent#, and for all overloads either

* [api]#khr::is_property_for_v<PropertyOrList, reduction># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, reduction># is [code]#true#.

_Effects (1)-(3):_ The same effect as the corresponding [code]#reduction#
overload with an identity value from the <<core-spec>> except that the
properties are specified by [code]#props#.

[[sec:khr-properties-reduction-properties]]
=== New reduction properties

This extension adds the following new style property that can be used with the
[code]#reduction# interface.

'''

.[apidef]#khr::initialize_to_identity#
[source,role=synopsis,id=api:khr-properties-initialize-to-identity]
----
namespace sycl::khr::property {

struct initialize_to_identity {
  constexpr initialize_to_identity(bool v = true) : value{v} {}
  bool value;
};

namespace key {
struct initialize_to_identity {};
}

} // namespace sycl::khr
----

When a reduction is created with this property and the [code]#value# is
[code]#true#, the effect is the same as if the reduction was created with
[code]#property::reduction::initialize_to_identity#.
If the [code]#value# is [code]#false#, this property has no effect on the
reduction.

The following traits inherit from [code]#std::true#:

* [code]#is_property<property::initialize_to_identity>#
* [code]#is_property_key<property::key::initialize_to_identity>#
* [code]#is_property_for<property::initialize_to_identity, reduction>#
* [code]#is_property_key_for<property::key::initialize_to_identity, reduction>#

[code]#property::initialize_to_identity# and
[code]#property::key::initialize_to_identity# are trivially copyable.

[[sec:khr-properties-kernel-bundle-additions]]
== Additions to the kernel bundle functions

This extension adds new property-accepting overloads to the free functions
[code]#compile#, [code]#link#, and [code]#build#.

These are free functions, not classes, so this extension defines an empty tag
type [code]#khr::kernel_bundle# to serve as the [code]#Class# parameter of the
[api]#khr::is_property_for# trait for properties that can be used with these
functions.

'''

[source,role=synopsis,id=api:khr-properties-kernel-bundle-tag]
----
namespace sycl::khr {

struct kernel_bundle; // tag type, never defined

} // namespace sycl::khr
----

[[sec:khr-properties-kernel-bundle-compile]]
=== New compile function overloads

This extension adds the following new overloads of the [code]#compile# function.

'''

[source,role=synopsis,id=api:khr-properties-compile]
----
namespace sycl {

template <typename PropertyOrList = khr::empty_properties_t>
kernel_bundle<bundle_state::object>
compile(const kernel_bundle<bundle_state::input>& inputBundle,            // (1)
        const std::vector<device>& devs, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
kernel_bundle<bundle_state::object>
compile(const kernel_bundle<bundle_state::input>& inputBundle,            // (2)
        PropertyOrList props = {});

} // namespace sycl
----

_Constraints:_ For both overloads, either

* [api]#khr::is_property_for_v<PropertyOrList, kernel_bundle># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, kernel_bundle># is
  [code]#true#.

_Effects (1)-(2):_ The same effect as the corresponding [code]#compile# overload
from the <<core-spec>> except that the properties are specified by [code]#props#.

[[sec:khr-properties-kernel-bundle-link]]
=== New link function overloads

This extension adds the following new overloads of the [code]#link# function.

'''

[source,role=synopsis,id=api:khr-properties-link]
----
namespace sycl {

template <typename PropertyOrList = khr::empty_properties_t>
kernel_bundle<bundle_state::executable>
link(const std::vector<kernel_bundle<bundle_state::object>>& objectBundles, // (1)
     const std::vector<device>& devs, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
kernel_bundle<bundle_state::executable>
link(const kernel_bundle<bundle_state::object>& objectBundle,             // (2)
     const std::vector<device>& devs, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
kernel_bundle<bundle_state::executable>
link(const std::vector<kernel_bundle<bundle_state::object>>& objectBundles, // (3)
     PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
kernel_bundle<bundle_state::executable>
link(const kernel_bundle<bundle_state::object>& objectBundle,             // (4)
     PropertyOrList props = {});

} // namespace sycl
----

_Constraints:_ For all overloads, either

* [api]#khr::is_property_for_v<PropertyOrList, kernel_bundle># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, kernel_bundle># is
  [code]#true#.

_Effects (1)-(4):_ The same effect as the corresponding [code]#link# overload
from the <<core-spec>> except that the properties are specified by [code]#props#.

[[sec:khr-properties-kernel-bundle-build]]
=== New build function overloads

This extension adds the following new overloads of the [code]#build# function.

'''

[source,role=synopsis,id=api:khr-properties-build]
----
namespace sycl {

template <typename PropertyOrList = khr::empty_properties_t>
kernel_bundle<bundle_state::executable>
build(const kernel_bundle<bundle_state::input>& inputBundle,              // (1)
      const std::vector<device>& devs, PropertyOrList props = {});

template <typename PropertyOrList = khr::empty_properties_t>
kernel_bundle<bundle_state::executable>
build(const kernel_bundle<bundle_state::input>& inputBundle,              // (2)
      PropertyOrList props = {});

} // namespace sycl
----

_Constraints:_ For both overloads, either

* [api]#khr::is_property_for_v<PropertyOrList, kernel_bundle># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, kernel_bundle># is
  [code]#true#.

_Effects (1)-(2):_ The same effect as the corresponding [code]#build# overload
from the <<core-spec>> except that the properties are specified by [code]#props#.

[[sec:khr-properties-kernel-bundle-properties]]
=== New kernel bundle properties

This extension defines no kernel bundle property.
The <<core-spec>> states that [code]#compile#, [code]#link#, and [code]#build#
accept a [code]#property_list# but does not itself define any such property; the
overloads above are added so that a future property (defined by an extension) can
be passed through the new style [code]#properties# mechanism.

[[sec:khr-properties-stream-additions]]
== Additions to the stream class

[[sec:khr-properties-stream-constructors]]
=== New stream constructors

This extension adds the following new constructor to the [code]#stream# class,
which allows a stream to be constructed with the new style properties defined in
this extension.

'''

[source,role=synopsis,id=api:khr-properties-stream]
----
namespace sycl {

class stream {
  template <typename PropertyOrList = khr::empty_properties_t>
  stream(std::size_t totalBufferSize, std::size_t workItemBufferSize,
         handler& cgh, PropertyOrList props = {});

  // ...
};

} // namespace sycl
----

_Constraints:_

* [api]#khr::is_property_for_v<PropertyOrList, stream># is [code]#true#, or
* [api]#khr::is_property_list_for_v<PropertyOrList, stream># is [code]#true#.

_Effects:_ The same effect as [code]#stream(totalBufferSize, workItemBufferSize,
cgh, propList)# from the <<core-spec>> except that the properties are specified by
[code]#props#.

[[sec:khr-properties-stream-properties]]
=== New stream properties

This extension defines no stream property.
The overload above is added so that a future stream property (defined by the
<<core-spec>> or by another extension) can be passed through the new style
[code]#properties# mechanism.

[[sec:khr-properties-examples-for-implementors]]
== Examples for implementors

This section demonstrates various common patterns for property definitions.
Implementors are encouraged to follow these patterns for properties that have
similar characteristics.

[[sec:khr-properties-examples-single-value]]
=== Properties with a single non-type value

When a property has a single value that is non-type, the name of the member
variable holding that value should be named [code]#value#.
This applies to both properties with runtime-supplied values and to properties
with compile-time constant values.

[source,,linenums]
----
namespace sycl::khr::property {

struct prop1 {
  constexpr prop1(int v) : value(v) {}
  int value;
};

template<int Value>
struct __unspecified_type__ {
  static constexpr int value = Value;
};

template<int Value>
inline constexpr __unspecified_type__<Value> prop2;

}
----

[[sec:khr-properties-examples-type-value]]
=== Properties with a type value

Properties that have a compile-time value may define the value as a type instead
of a constant.
In such cases, the property defines a member type alias to hold the property's
value instead of a static constexpr member variable.
When a property has a single value that is a type, the name of the member type
alias should be [code]#value_t#.

[source,,linenums]
----
namespace sycl::khr::property {

template<typename Value>
struct __unspecified_type__ {
  using value_t = Value;
};

template<typename Value>
inline constexpr __unspecified_type__<Value> prop;

}
----

[[sec:khr-properties-examples-compile-time-enumeration]]
=== Compile-time properties with an enumeration

When a property has a single compile-time constant value that is a small
enumeration, it is recommended to define a property variable for each of the
enumerators.

[source,,linenums]
----
namespace sycl::khr::property {

enum class access_type {read, write};

template<access_type Access>
struct __unspecified_type__ {
  static constexpr access_type value = Access;
};

// Define a property variable for each enumerator to reduce verbosity in
// application code.
inline constexpr __unspecified_type__<access_type::read> access_read;
inline constexpr __unspecified_type__<access_type::write> access_write;

// There should still be a variable template to enable applications that set
// the value via metaprogramming.
template<access_type Access>
inline constexpr __unspecified_type__<Access> access;

}
----

[[sec:khr-properties-examples-boolean]]
=== Boolean properties

When a property is a boolean flag, it is recommended to define the property with
a boolean value, rather than relying on the existence of the property to convey
the flag.
This recommendation applies to both properties with runtime-supplied values and
to properties with compile-time constant values.
For example, two hypothetical boolean properties could be defined like this:

[source,,linenums]
----
namespace sycl::khr::property {

struct enable_thing1 {
  constexpr enable_thing1(bool enable) : value(enable) {}
  bool value;
};

template<bool Enable>
struct __unspecified_type__ {
  static constexpr bool value = Enable;
};

template<bool Enable>
inline constexpr __unspecified_type__<Enable> enable_thing2;

}
----

An application can then select whether the properties are on or off using code
like this:

[source,,linenums]
----
bool thing1 = /* determine at runtime if thing1 is enabled */;

#ifdef THING2
constexpr bool thing2 = true;
#else
constexpr bool thing2 = false;
#endif

sycl::khr::properties props{
  sycl::khr::property::enable_thing1{thing1},
  sycl::khr::property::enable_thing2<thing2>,
};
// use "props"
----

If we did not use this pattern, an application would have to define two
different [code]#props# variables like this because the type of [code]#props# is
different depending on whether it contains the [code]#enable_thing1# property.

[source,,linenums]
----
bool thing1 = /* determine at runtime if thing1 is enabled */;

if (thing1) {
  sycl::khr::properties props{
    sycl::khr::property::enable_thing1,
#ifdef THING2
    sycl::khr::property::enable_thing2
#endif
  };
  // use "props"
}
else {
  sycl::khr::properties props{
#ifdef THING2
    sycl::khr::property::enable_thing2
#endif
  };
  // use "props"
}
----

[[sec:khr-properties-limitations]]
== Limitations

This extension does not define [code]#operator==# or [code]#operator!=# for the
[code]#properties# class, and a [code]#properties# list does not follow the
common reference semantics or the common by-value semantics defined by the
<<core-spec>>.
Two [code]#properties# lists constructed from the same set of properties may
have different types when the properties are specified in a different order.
Applications can query a [code]#properties# list with [code]#has_property# and
[code]#get_property# (for example, by using [code]#decltype#).

[[sec:khr-properties-issues]]
== Issues

* Do we want to extend the kernel bundle functions ([code]#compile#,
  [code]#link#, [code]#build#) with new-style property support at all?
  The <<core-spec>> states that it defines no [code]#compile#, [code]#link#, or
  [code]#build# property and that such properties may be specified by a vendor
  extension.
  This extension therefore adds the property-accepting overloads only as a
  vehicle for a future property; no kernel bundle property is defined today.
  As with the accessor classes, the benefit of adding these overloads now is
  small relative to the surface they introduce, so we should decide whether to
  keep them or omit the kernel bundle additions until an actual property exists.

* For the USM allocation entry points, is a single tag type
  [code]#khr::usm_allocation# the right way to express property applicability, or
  should the [code]#usm_allocator# class (which is a real class) be used directly
  as the [code]#Class# operand, with the tag reserved for the free allocation
  functions only?
  This extension currently keys both the [code]#usm_allocator# constructors and
  the free allocation functions on the single [code]#usm_allocation# tag, on the
  assumption that a USM property would apply to the whole allocation domain.

* Do we want to extend the accessor classes with new-style property support at
  all?
  The [code]#accessor#, [code]#host_accessor#, [code]#unsampled_image_accessor#,
  and [code]#host_unsampled_image_accessor# classes each take a
  [code]#property_list# parameter on their constructors in the <<core-spec>>, but
  the only property presently usable with an accessor is [code]#no_init#.
  Adding a [code]#PropertyOrList# overload for every accessor constructor
  (placeholder vs. bound, the deduction tags, ranged vs. non-ranged, the various
  access targets) would add substantial API surface for a single property, so
  this extension currently adds nothing to the accessor classes (the section is
  left empty).
  If we do decide to add it, what is the preferred way to specify "every
  constructor that takes a [code]#property_list# also has an overload taking a
  [code]#PropertyOrList#" without enumerating all of the accessor constructors
  individually?

* In the core spec, the [code]#unsampled_image# and [code]#sampled_image#
  classes have a [code]#property_list# parameter for their [code]#get_access#
  and [code]#get_host_access# member functions.
  However, the [code]#buffer# class does not.
  This seems like a weird inconsistency.
  Should this KHR provide new overloads of [code]#unsampled_image::get_access#,
  [code]#unsampled_image::get_host_access#, etc. that take the new-style
  properties list?
  Or, do we consider it a mistake that we added the [code]#property_list#
  parameter to these functions in the core spec, in which case we wouldn't want
  to propagate that mistake into this KHR.
  In my opinion, all of the [code]#get_access# and [code]#get_host_access#
  member functions should be deprecated in favor of the pattern where the
  application constructs an [code]#accessor# or [code]#host_accessor# from the
  image or buffer.
