// %%%%%%%%%%%%%%%%%%%%%%%%%%%% begin compiler_abi %%%%%%%%%%%%%%%%%%%%%%%%%%%%

[[chapter.device.compiler]]
= SYCL Device Compiler

This section specifies the requirements of the SYCL device compiler.
Most features described in this section relate to underlying <<backend>>
capabilities of target devices and limiting the requirements of device code to
ensure portability.


== Offline compilation of SYCL source files

There are two alternatives for a SYCL <<device-compiler>>: a
[keyword]#single-source device compiler# and a device compiler that supports the
technique of <<smcp>>.

A SYCL device compiler takes in a {cpp} source file, extracts only the SYCL
kernels and outputs the device code in a form that can be enqueued from host
code by the associated <<sycl-runtime>>.
How the <<sycl-runtime>> invokes the kernels is implementation-defined, but a
typical approach is for a device compiler to produce a header file with the
compiled kernel contained within it.
By providing a command-line option to the host compiler, it would cause the
implementation's SYCL header files to [code]#{hash}include# the generated header
file.
The SYCL specification has been written to allow this as an implementation
approach in order to allow <<smcp>>.
However, any of the mechanisms needed from the SYCL compiler, the
<<sycl-runtime>> and build system are implementation-defined, as they can vary
depending on the platform and approach.

A SYCL single-source device compiler takes in a {cpp} source file and compiles
both host and device code at the same time.
This specification specifies how a SYCL single-source device compiler sees and
outputs device code for kernels, but does not specify the host compilation.


[[sec:naming.kernels]]
== Naming of kernels

SYCL kernels are extracted from {cpp} source files and stored in an
implementation-defined format.
In the case of the shared-source compilation model, the kernels have to be
uniquely identified by both host and device compiler.
This is required in order for the host runtime to be able to load the kernel by
using a backend-specific host runtime interface.

From this requirement the following rules apply for naming the kernels:

  * The kernel name is a [keyword]#{cpp} typename#.
  * The kernel name must be forward declarable at namespace scope (including
    global namespace scope) and may not be forward declared other than at
    namespace scope.
    If it isn't forward declared but is specified as a template argument in a
    kernel invoking interface, as described in <<subsec:invokingkernels>>, then
    it may not conflict with a name in any enclosing namespace scope.

[NOTE]
====
The requirement that a kernel name be forward declarable makes some types for
kernel names illegal, such as anything declared in the [code]#std# namespace
(adding a declaration to namespace [code]#std# leads to undefined behavior).
====

  * If the kernel is defined as a named function object type, the name can be
    the typename of the function object as long as it is either declared at
    namespace scope, or does not conflict with any name in an enclosing
    namespace scope.
  * If the kernel is defined as a lambda, a typename can optionally be provided
    to the kernel invoking interface as described in <<subsec:invokingkernels>>,
    so that the developer can control the kernel name for purposes such as
    debugging or referring to the kernel when applying build options.
  * If a kernel function relies on template parameters, then those template
    parameters must be contained by the kernel name.
    If such a kernel name is specified as a template argument in a kernel
    invoking interface, then the template parameters on which the kernel depends
    must be forward declarable at namespace scope.

In both single-source and shared-source implementations, a device compiler
should detect the kernel invocations (e.g. [code]#parallel_for<kernelname>)# in
the source code and compile the enclosed kernels, storing them with their
associated type name.

The format of the kernel and the compilation techniques are details of an
implementation and not specified.
The interface between the compiler and the runtime for extracting and executing
SYCL kernels on the device is a detail of an implementation and not specified.


== Compilation of functions

The SYCL device compiler parses an entire {cpp} source file supplied by the
user, including any header files referenced via [code]#{hash}include#
directives.
From this source file, the SYCL device compiler must compile kernels for the
device, as well as any functions that the kernels call.

The device compiler identifies kernels by looking for calls to
<<kernel-invocation-command, Kernel invocation commands>> such as
[code]#parallel_for#.
One of the parameters is a function object which is known as a
<<sycl-kernel-function>>, and this function must always return [code]#void#.
Any function called by the <<sycl-kernel-function>> is also compiled for the
device, and these functions together with the <<sycl-kernel-function, SYCL
kernel functions>> are known as <<device-function, device functions>>.
The device compiler searches recursively for any functions called from a
<<device-function>>, and these functions are also compiled for the device and
known as <<device-function, device functions>>.

To illustrate, the following source code shows three functions and a kernel
invoke with comments explaining which functions need to be compiled for the
device.

[source,,linenums]
----
void f(handler& cgh) {
  // Function "f" is not compiled for device

  cgh.single_task([=] {
    // This code is compiled for device
    g(); // This line forces "g" to be compiled for device
  });
}

void g() {
  // Called from kernel, so "g" is compiled for device
}

void h() {
  // Not called from a device function, so not compiled for device
}
----

In order for the SYCL device compiler to correctly compile <<device-function,
device functions>>, all functions in the source file, whether <<device-function,
device functions>> or not, must be syntactically correct functions according to
this specification.
A syntactically correct function adheres to at least the minimum required {cpp}
version defined in <<sec:progmodel.minimumcppversion>>.


[[sec:language.restrictions.kernels]]
== Language restrictions for device functions

<<device-function, Device functions>> must abide by certain restrictions.
The full set of {cpp} features are not available to these functions.
Following is a list of these restrictions:

  * Pointers and objects containing pointers may be shared.
    However, when a pointer is passed between SYCL devices or between the host
    and a SYCL device, dereferencing that pointer on the device produces
    undefined behavior unless the device supports <<usm>> and the pointer is an
    address within a <<usm>> memory region (see <<sec:usm>>).
  * Memory storage allocation is not allowed in kernels.
    All memory allocation for the device is done on the host using accessor
    classes or using <<usm>> as explained in <<sec:usm>>.
    Consequently, the default allocation [code]#operator new# overloads that
    allocate storage are disallowed in a SYCL kernel.
    The placement [code]#new# operator and any user-defined overloads that do
    not allocate storage are permitted.
  * Kernel functions must always have a [code]#void# return type.
    A kernel lambda trailing-return-type that is not [code]#void# is therefore
    illegal, as is a return statement (that would return from the kernel
    function) with an expression that does not convert to [code]#void#.
  * The odr-use of polymorphic classes and classes with virtual inheritance is
    allowed.
    However, no virtual member functions are allowed to be called in a
    <<device-function>>.
  * No function pointers or references are allowed to be called in a
    <<device-function,device function>>.
  * RTTI is disabled inside <<device-function,device functions>>.
  * No variadic functions are allowed to be called in a <<device-function>>.
  * Exception-handling cannot be used inside a <<device-function>>.
    [code]#noexcept# is allowed.
  * Recursion is not allowed in a <<device-function>>.
  * Variables with thread storage duration ([code]#thread_local# storage class
    specifier) are not allowed to be odr-used in a <<device-function>>.
  * Variables with static storage duration that are odr-used inside a
    <<device-function>>, must be either [code]#const# or [code]#constexpr#, and
    must also be either zero-initialized or constant-initialized.

[NOTE]
====
Amongst other things, this restriction makes it illegal for a
<<device-function>> to access a global variable that isn't [code]#const# or
[code]#constexpr#.
====

  * The rules for kernels apply to both the kernel function objects themselves
    and all functions, operators, member functions, constructors and destructors
    called by the kernel.
    This means that kernels can only use library functions that have been
    adapted to work with SYCL.
    Implementations are not required to support any library routines in kernels
    beyond those explicitly mentioned as usable in kernels in this spec.
    Developers should refer to the SYCL built-in functions in <<sycl:builtins>>
    to find functions that are specified to be usable in kernels.
  * Interacting with a special <<sycl-runtime>> class (e.g. SYCL
    [code]#accessor# or [code]#stream#) that is stored within a {cpp} union is
    undefined behavior.
  * Any variable or function that is odr-used from a <<device-function>> must be
    defined in the same translation unit as that use.
    However, a function may be defined in another translation unit if the
    implementation defines the [code]#SYCL_EXTERNAL# macro as described in
    <<subsec:syclexternal>>.

Inside a <<discarded-statement>> or in the case of a
<<manifestly-constant-evaluated>>, any code accepted by the C++ standard in this
case is also accepted in a SYCL <<device-function>>.

[NOTE]
====
The restriction waiver in <<discarded-statement>> or
<<manifestly-constant-evaluated>> allows any kind of meta-programming in a
<<device-function>>.
====

[[subsec:scalartypes]]
== Built-in scalar data types

In a SYCL device compiler, the device definition of all standard {cpp}
fundamental types from <<table.types.fundamental>> must match the host
definition of those types, in both size and alignment.
A device compiler may have this preconfigured so that it can match them based on
the definitions of those types on the platform, or there may be a necessity for
a device compiler command-line option to ensure the types are the same.

The standard {cpp} fixed width types, e.g. [code]#int8_t#, [code]#int16_t#,
[code]#int32_t#,[code]#int64_t#, should have the same size as defined by the
{cpp} standard for host and device.


[[table.types.fundamental]]
.Fundamental data types supported by SYCL
[width="100%",options="header",separator="@",cols="65%,35%"]
|====
@ Fundamental data type @ Description
a@
[source]
----
bool
----
   a@ A conditional data type which can be either true or false. The value
      true expands to the integer constant 1 and the value false expands to the
      integer constant 0.

a@
[source]
----
char
----
   a@ A signed or unsigned 8-bit integer, as defined by the {cpp} core language

a@
[source]
----
signed char
----
   a@ A signed 8-bit integer, as defined by the {cpp} core language

a@
[source]
----
unsigned char
----
   a@ An unsigned 8-bit integer, as defined by the {cpp} core language

a@
[source]
----
short int
----
   a@ A signed integer of at least 16-bits, as defined by the {cpp} core language

a@
[source]
----
unsigned short int
----
   a@ An unsigned integer of at least 16-bits, as defined by the {cpp} core language

a@
[source]
----
int
----
   a@ A signed integer of at least 16-bits, as defined by the {cpp} core language

a@
[source]
----
unsigned int
----
   a@ An unsigned integer of at least 16-bits, as defined by the {cpp} core language

a@
[source]
----
long int
----
   a@ A signed integer of at least 32-bits, as defined by the {cpp} core language

a@
[source]
----
unsigned long int
----
   a@ An unsigned integer of at least 32-bits, as defined by the {cpp} core language

a@
[source]
----
long long int
----
   a@ An integer of at least 64-bits, as defined by the {cpp} core language

a@
[source]
----
unsigned long long int
----
   a@ An unsigned integer of at least 64-bits, as defined by the {cpp} core language

a@
[source]
----
float
----
   a@ A 32-bit floating-point. The float data type must conform to the IEEE 754
      single precision storage format.

a@
[source]
----
double
----
   a@ A 64-bit floating-point. The double data type must conform to the IEEE 754
      double precision storage format.  This type is only supported on devices
      that have [code]#aspect::fp64#.

|====



== Preprocessor directives and macros

The standard {cpp} preprocessing directives and macros are supported.
The following preprocessor macros must be defined by all conformant
implementations:

  * [code]#SYCL_LANGUAGE_VERSION# is defined to an integer literal that
    indicates the version of the SYCL specification to which the implementation
    conforms.
+
[width="100%",options="header",separator="@",cols="50%,50%"]
|====
@ SYCL version @ Macro defined as
a@ SYCL 2020 a@ [code]#202012L#
a@ SYCL {SYCL_VERSION} a@ [code]#{SYCL_LANGUAGE_VERSION}L#
|====
+
Future versions of the SYCL specification will define this macro to an integer
literal with greater value.
  * [code]#SYCL_DEVICE_COPYABLE# is defined to 1 if the implementation supports
    explicitly specified <<device-copyable>> types as described in
    <<sec::device.copyable>>.
    Otherwise, the implementation's definition of device copyable falls back to
    {cpp} trivially copyable and [code]#sycl::is_device_copyable# is ignored;
  * [code]#+__SYCL_DEVICE_ONLY__+# is defined to 1 if the source file is being
    compiled with a SYCL device compiler which does not produce host binary;
  * [code]#+__SYCL_SINGLE_SOURCE__+# is defined to 1 if the source file is being
    compiled with a SYCL single-source compiler which produces host as well as
    device binary;
  * [code]#SYCL_FEATURE_SET_FULL# is defined to 1 if the SYCL implementation
    supports the full feature set and is not defined otherwise.
    For more details see <<cha:feature-sets>>;
  * [code]#SYCL_FEATURE_SET_REDUCED# is defined to 1 if the SYCL implementation
    supports the reduced feature set and not the full feature set, otherwise it
    is not defined.
    For more details see <<cha:feature-sets>>;
  * [code]#SYCL_EXTERNAL# is an optional macro which enables external linkage of
    SYCL functions and member functions to be included in a SYCL kernel.
    The macro is only defined if the implementation supports external linkage.
    For more details see <<subsec:syclexternal>>.

In addition, for each <<backend>> supported, the preprocessor macros described
in <<sec:backends>> must be defined by all conformant implementations.


[[sec:optional-kernel-features]]
== Optional kernel features

A number of kernel features defined by this SYCL specification are optional;
they may be supported on some devices but not on other devices.

As stated in <<sec:language.restrictions.kernels>>, the restrictions for
optional kernel features do not apply to discarded statements or to manifestly
constant-evaluated expressions or conversions in device code.
Device code may use optional features in <<discarded-statement>> or
<<manifestly-constant-evaluated>> even if the device does not support the
optional feature.

As described in <<sec:device-aspects>>, an application can test whether a device
supports an optional feature by testing whether the device has an associated
aspect.
The following aspects are those that correspond to optional kernel features:

  * [code]#fp16#
  * [code]#fp64#
  * [code]#atomic64#

In addition, the following {cpp} attributes from <<sec:kernel.attributes>> also
correspond to optional kernel features because they force the kernel to be
compiled in a way that might not run on all devices:

  * [code]#reqd_work_group_size()#
  * [code]#reqd_sub_group_size()#

In order to guarantee source code portability of SYCL applications that use
optional kernel features, all SYCL implementations must be able to compile
device code that uses these optional features regardless of whether the
implementation supports the features on any of its devices.

Of course, applications that make use of optional kernel features should ensure
that a kernel using such a feature is submitted only to a device that supports
the feature.
If the application submits a <<command-group>> using a secondary queue, then any
kernel submitted from the <<command-group>> should use only features that are
supported by both the primary queue's device and the secondary queue's device.
If an application fails to do this, the implementation must throw a synchronous
exception with the [code]#errc::kernel_not_supported# error code from the
<<kernel-invocation-command>> (e.g. [code]#parallel_for()#).

It is legal for a SYCL application to define several kernels in the same
translation unit even if they use different optional features, as shown in the
following example:

[source,,linenums]
----
include::{code_dir}/twoOptionalFeatures.cpp[lines=4..-1]
----

An implementation may not raise a compile time diagnostic or a run time
exception merely due to speculative compilation of a kernel for a device when
the application does not actually submit the kernel to that device.
To illustrate using the example above, assume that device [code]#dev1# does not
have [code]#aspect::atomic64# and device [code]#dev2# does not have
[code]#aspect::fp16#.
An implementation cannot raise a diagnostic due to compilation of
[code]#KernelA# for device [code]#dev2# or for compilation of [code]#KernelB#
for device [code]#dev1# because the application does not submit these kernels to
those devices.

[NOTE]
====
It is expected that this requirement will have an impact on the way an
implementation bundles kernels into device images.
For example, naively bundling [code]#KernelA# and [code]#KernelB# into the same
device image could run afoul of this requirement if the implementation compiles
the entire device image when [code]#KernelA# is submitted to device
[code]#dev1#.
====


[[sec:device.attributes]]
== Attributes for device code

{cpp} attributes may be used to decorate kernels and device functions in order
to influence the code generated by the device compiler.
These attributes are all defined in the [code]#+[[sycl::]]+# namespace.

If one of the attributes defined in this section is applied to a kernel or
device function, it must be applied to the first declaration of that kernel or
device function in the translation unit.
Programs which fail to do this are ill formed and the compiler must issue a
diagnostic.
Redeclarations of the kernel or device function in the same translation unit may
optionally have the same attribute applied (so long as the attribute arguments
are the same between the declarations), but this is not required.
The attribute remains in effect regardless of whether it appears in the
redeclaration.

Unless an attribute's description specifically allows it, a kernel or device
function may not be declared with the more than one instance of the same
attribute unless all instances have the same attribute arguments.
The compiler must issue a diagnostic for programs which violate this
requirement.
When two or more instances of the same attribute appear on the declaration of a
kernel or device function, the effect is as though a single instance appeared
(assuming that all instances have the same attribute arguments).

If a kernel or device function is declared with an attribute in one translation
unit and the same kernel or device function is declared without the same
attribute (and its same attribute arguments) in another translation unit, the
program is ill formed and no diagnostic is required.

If any of these attributes are applied to a device function that is also
compiled for the host, they have no effect when the function is compiled for the
host.

Applying these attributes to any language construct other than those specified
in this section has implementation-defined effect.


[[sec:kernel.attributes]]
=== Kernel attributes

The attributes listed in <<table.kernel.attributes>> have a different position
depending on whether the kernel is defined as a lambda expression or as a named
function object.
If the kernel is a named function object, the attribute is applied to the
declarator-id in the function declaration.
However, if the kernel is a lambda expression, the attribute is applied to the
lambda declarator.

[NOTE]
====
The reason for the different positions is because the {cpp} core language does
not currently define a position for attributes to appertain to the lambda's
corresponding function operator or operator template, only to the corresponding
_type_ of the function operator or operator template.
This is expected to be remedied in a future version of the {cpp} core language
specification.
====

The example below demonstrates these attribute positions using the
[code]#[[sycl::reqd_work_group_size(16)]]# attribute.
Note that the {cpp} core language allows two possible positions for kernels that
are defined as a named function object.

[source,,linenums]
----
include::{code_dir}/attributes.cpp[lines=4..-1]
----

[[table.kernel.attributes]]
.Attributes for kernel functions
[width="100%",options="header",separator="@",cols="65%,35%"]
|====
@ SYCL attribute @ Description
a@
[source]
----
reqd_work_group_size(dim0)
reqd_work_group_size(dim0, dim1)
reqd_work_group_size(dim0, dim1, dim2)
----
   a@ Indicates that the kernel must be launched with the specified work-group
      size.  The number of arguments must match the dimensionality of the
      work-group used to invoke the kernel, and the order of the arguments
      matches the order of the dimension extents to the [code]#range#
      constructor.  Each argument must be an integral constant expression that
      is representable by [code]#size_t#.

Kernels that are decorated with this attribute may not call functions that are
defined in another translation unit via the [code]#SYCL_EXTERNAL# macro.

Each device may have limitations on the work-group sizes that it supports.  If
a kernel is decorated with this attribute and then submitted to a device that
does not support the work-group size, the implementation must throw a
synchronous [code]#exception# with the [code]#errc::kernel_not_supported# error
code.  If the kernel is submitted to a device that does support the work-group
size, but the application provides an [code]#nd_range# that does not match the
size from the attribute, then the implementation must throw a synchronous
[code]#exception# with the [code]#errc::nd_range# error code.

a@
[source]
----
work_group_size_hint(dim0)
work_group_size_hint(dim0, dim1)
work_group_size_hint(dim0, dim1, dim2)
----
   a@ Provides a hint to the compiler about the work-group size most likely to
      be used when launching the kernel at runtime.  The number of arguments
      must match the dimensionality of the work-group used to invoke the
      kernel, and the order of the arguments matches the order of the dimension
      extents to the [code]#range# constructor.  Each argument must be an
      integral constant expression that is representable by [code]#size_t#.
      The effect of this attribute, if any, is implementation-defined.

a@
[source]
----
vec_type_hint(<type>)
----
   a@ Hint to the compiler on the vector computational width of of the kernel. The
      argument must be one of the vector types defined in <<sec:vector.type>>.
      The effect of this attribute, if any, is implementation-defined.

This attribute is deprecated (available for use, but will likely be removed in
a future version of the specification and is not recommended for use in new code).

a@
[source]
----
reqd_sub_group_size(size)
----
   a@ Indicates that the kernel must be compiled and executed with the specified
      sub-group size. The argument to the attribute must be an integral constant
      expression that is representable by [code]#uint32_t#.

Kernels that are decorated with this attribute may not call functions that are
defined in another translation unit via the [code]#SYCL_EXTERNAL# macro.

Each device supports only certain sub-group sizes as defined by
[code]#info::device::sub_group_sizes#.  In addition, some device features may
be incompatible with certain sub-group sizes.  If a kernel is decorated with
this attribute and then submitted to a device that does not support the
sub-group size or if the kernel uses a feature that the device does not support
with this sub-group size, the implementation must throw a synchronous
[code]#exception# with the [code]#errc::kernel_not_supported# error code.

a@
[source]
----
device_has(aspect, ...)
----
   a@ This attribute may be used to decorate either the declaration of a kernel
      function that is defined in the current translation unit or to decorate
      the declaration of a non-kernel device function.  The following
      description applies when the attribute decorates a kernel function.

The parameter list to the [code]#sycl::device_has()# attribute consists of zero
or more integral constant expressions, where each integer is interpreted as one
of the enumerated values in the [code]#sycl::aspect# enumeration type.

Specifying this attribute on a kernel has two effects.  First, it causes the
<<kernel-invocation-command>> to throw a synchronous exception with the
[code]#errc::kernel_not_supported# error code if the kernel is submitted to a
device that does not have one of the listed aspects.  (This includes the device
associated with the secondary queue if the kernel is submitted from a
<<command-group>> that has a secondary queue.)  Second, it causes the compiler
to issue a diagnostic if the kernel (or any of the functions it calls) uses an
optional feature that is associated with an aspect that is not listed in the
attribute.

The value of each parameter to this attribute must be equal to one of the
values in the [code]#sycl::aspect# enumeration type (including any extended
values the implementation may provide).  If it does not, the program is ill
formed and the compiler must issue a diagnostic.

See below for an example of this attribute.

|====

.Example of the [code]#sycl::device_has()# attribute
[source,,linenums]
----
include::{code_dir}/deviceHas.cpp[lines=4..-1]
----


=== Device function attributes

The attributes in <<table.device.attributes>> are applied to the declaration of
a non-kernel device function.
The position of the attribute is the same as for the kernel function attributes
defined above in <<sec:kernel.attributes>>.

[[table.device.attributes]]
.Attributes for non-kernel device functions
[width="100%",options="header",separator="@",cols="65%,35%"]
|====
@ SYCL attribute @ Description
a@
[source]
----
device_has(aspect, ...)
----
   a@ This attribute may be used to decorate either the declaration of a kernel
      function that is defined in the current translation unit or to decorate
      the declaration of a non-kernel device function.  The following
      description applies when the attribute decorates a non-kernel device
      function declaration.

The syntax of this attribute's parameter list is the same as the syntax for
the form of [code]#sycl::device_has()# that is specified on a kernel function
(see <<table.kernel.attributes>>).

This attribute is required when a non-kernel device function that uses optional
device features is called in one translation unit and defined in another
translation unit via the [code]#SYCL_EXTERNAL# macro.

When this attribute appears in a translation unit that calls the decorated
device function, it is an assertion that the device function uses optional
features that correspond to the aspects listed in the attribute.  The program
is ill formed if the called device function uses optional features that do not
correspond to any of the aspects listed in the attribute, or if the function
uses optional features and the attribute is not specified.  No diagnostic is
required in this case.

When this attribute appears in a translation unit that defines the decorated
device function, it causes the compiler to issue a diagnostic if the device
function (or any of the functions it calls) uses an optional feature that is
associated with an aspect that is not listed in the attribute.

|====


== Address-space deduction

{cpp} has no type-level support to represent address spaces.
As a consequence, the SYCL generic programming model does not directly affect
the {cpp} type of unannotated pointers and references.

Source level guarantees about address spaces in the SYCL generic programming
model can only be achieved using pointer classes (instances of
[code]#multi_ptr#), which are regular classes that represent pointers to data
stored in the corresponding address spaces.

In SYCL, the address space of pointer and references are derived from:

  * Accessors that give access to shared data.
    They can be bound to a memory object in a command group and passed into a
    kernel.
    Accessors are used in scheduling of kernels to define ordering.
    Accessors to buffers have a compile-time address space based on their access
    mode.
  * Explicit pointer classes (e.g. [code]#global_ptr#) holds a pointer which is
    known to be addressing the address space represented by the
    [code]#access::address_space#.
    This allows the compiler to determine whether the pointer references global,
    local, constant or private memory and generate code accordingly.
  * Raw {cpp} pointer and reference types (e.g. [code]#int*#) are allowed within
    SYCL kernels.
    They can be constructed from the address of local variables, explicit
    pointer classes, or accessors.


[[subsec:addrspaceAssignment]]
=== Address space assignment

In order to understand where data lives, the device compiler is expected to
assign address spaces while lowering types for the underlying target based on
the context.
Depending on the <<backend, SYCL backends>> and mode, address space deducing
rules differ slightly.

If the target of the SYCL backend can represent the generic address space, then
the "common address space deduction rules" in <<subsec:commonAddressSpace>> and
the "generic as default address space rules" in <<subsec:genericAddressSpace>>
apply.
If the target of the SYCL backend cannot represent the generic address space,
then the "common address space deduction rules" in <<subsec:commonAddressSpace>>
and the "inferred address space rules" in <<subsec:inferredAddressSpace>> apply.

[NOTE]
====
SYCL address space does not affect the type, address space shall be understood
as memory segment in which data is allocated.
For instance, if [code]#int i;# is allocated to the global address space, then
[code]#decltype(&i)# shall evaluate to [code]#int*#.
====


[[subsec:commonAddressSpace]]
=== Common address space deduction rules

The variable declarations get assigned to an address space depending on their
scope and storage class:

  * Namespace scope
  ** If the type is [code]#const#, the declaration is assigned to an
     implementation-defined address space.
     If the target of the SYCL backend can represent the generic address space,
     then the assigned address space must be compatible with the generic address
     space.

[NOTE]
====
Namespace scope non-[code]#const# declarations cannot be used within a kernel,
as restricted in <<sec:language.restrictions.kernels>>.
This means that non-[code]#const# global variables cannot be accessed by any
device kernel or code called by the device kernel.
====

  * Block scope and function parameter scope
  ** Declarations with static storage duration are treated the same way as
     variables in namespace scope
  ** Otherwise the declaration is assigned to the local address space if
     declared in a hierarchical context
  ** Otherwise the declaration is assigned to the private address space
  * Class scope
  ** Static data members are treated the same way as for variable in namespace
     scope

If a prvalue-to-xvalue conversion happens as part of an initialization
expression, then the result is assigned to the same address space as the entity
being initialized.
Otherwise, if the conversion happens in a block scope or function parameter
scope, the result is assigned to the local address space if it happens in a
hierarchical context otherwise it is assigned to the private address space.
It the prvalue-to-xvalue conversion happens in another scope, the result is
assigned in the same way as declaration in namespace scope.


[[subsec:genericAddressSpace]]
=== Generic as default address space

For SYCL backends that can represent the generic address space (see
<<subsec:addrspaceAssignment>>), unannotated pointers and references are
considered to be pointing to the generic address space.


[[subsec:inferredAddressSpace]]
=== Inferred address space

[NOTE]
.Note for this version
====
The address space deduction feature described next is inherited from the SYCL
1.2.1 specifications.
This section will be changed in a future version to better align with addition
of generic address space and generic as default address space.
====

For SYCL backends that cannot represent the generic address space (see
<<subsec:addrspaceAssignment>>), inside kernels the SYCL device compiler will
need to auto-deduce the memory region of unannotated pointer and reference types
during the lowering of types from {cpp} to the underlying representation.

If a kernel function or device function contains a pointer or reference type,
then the address space deduction must be attempted using the following rules:

  * If an explicit pointer class is converted into a {cpp} pointer value, then
    the {cpp} pointer value will point to same address space as the one
    represented by the explicit pointer class.
  * If a variable is declared as a pointer type, but initialized in its
    declaration to a pointer value with an already-deduced address space, then
    that variable will have the same address space as its initializer.
  * If a function parameter is declared as a pointer type, and the argument is a
    pointer value with a deduced address space, then the function will be
    compiled as if the parameter had the same address space as its argument.
    It is legal for a function to be called in different places with different
    address spaces for its arguments: in this case the function is said to be
    "`duplicated`" and compiled multiple times.
    Each duplicated instance of the function must compile legally in order to
    have defined behavior.
  * If a function return type is declared as a pointer type and return
    statements use address space deduced expressions, then the function will be
    compiled as if the return type had the same address space.
    To compile legally, all return expressions must deduce to the same address
    space.
  * The rules for pointer types also apply to reference types.
    i.e. a reference variable takes its address space from its initializer.
    A function with a reference parameter takes its address space from its
    argument.
  * If no other rule above can be applied to a declaration of a pointer, then it
    is assumed to be in the private address space.

It is illegal to assign a pointer value addressing one address space to a
pointer variable addressing a different address space.


== SYCL offline linking

// Jon: Section empty, but subsection has content? Odd choice.


[[subsec:syclexternal]]
=== SYCL functions and member functions linkage

By default, any function that is odr-used from a <<device-function>> must be
defined in the same translation unit as that use.
However, this restriction is relaxed if both of the following conditions are
met:

* The implementation defines the [code]#SYCL_EXTERNAL# macro;
* The translation unit that calls the function declares the function with
  [code]#SYCL_EXTERNAL# as described below.

When a function is declared with [code]#SYCL_EXTERNAL#, that macro must be used
on the first declaration of that function in the translation unit.
Redeclarations of the function in the same translation unit may optionally use
[code]#SYCL_EXTERNAL#, but this is not required.

When a function is declared with [code]#SYCL_EXTERNAL#, that function must also
be defined in some translation unit, where the function is declared with
[code]#SYCL_EXTERNAL#.

A function may only be declared with [code]#SYCL_EXTERNAL# if it has external
linkage by normal C++ rules.

A function declared with [code]#SYCL_EXTERNAL# may be called from both host and
device code.
The macro has no effect when the function is called from host code.

In order to declare a function with [code]#SYCL_EXTERNAL#, the macro name
[code]#SYCL_EXTERNAL# must appear before the function declaration.
If the function is also decorated with {cpp} attributes that appear before the
declaration, the [code]#SYCL_EXTERNAL# may appear before, after, or between
these attributes.
The following example demonstrates the use of [code]#SYCL_EXTERNAL#.

[source,,linenums]
----
include::{code_dir}/sycl-external.cpp[lines=4..-1]
----

Functions that are declared using [code]#SYCL_EXTERNAL# have the following
additional restrictions beyond those imposed on other device functions:

* If the SYCL backend does not support the generic address space then the
  function cannot use raw pointers as parameter or return types.
  Explicit pointer classes must be used instead;

* The function cannot call [code]#group::parallel_for_work_item#;

* The function cannot be called from a [code]#parallel_for_work_group# scope.

// %%%%%%%%%%%%%%%%%%%%%%%%%%%% end compiler_abi %%%%%%%%%%%%%%%%%%%%%%%%%%%%
