// %%%%%%%%%%%%%%%%%%%%%%%%%%%% begin descriptors %%%%%%%%%%%%%%%%%%%%%%%%%%%%

[appendix]
[[sec:information-descriptors]]
= Information descriptors

This appendix contains the definitions of all the SYCL information descriptors
introduced in <<chapter:sycl-programming-interface>>.

[[appendix.platform.descriptors]]
== Platform information descriptors

The following interface includes all the information descriptors for the
[code]#platform# class.
[source,,linenums]
----
include::{header_dir}/platformInfo.h[lines=4..-1]
----


[[appendix.context.descriptors]]
== Context information descriptors

The following interface includes all the information descriptors for the
[code]#context# class.
[source,,linenums]
----
include::{header_dir}/contextInfo.h[lines=4..-1]
----


[[appendix.device.descriptors]]
== Device information descriptors

The following interface includes all the information descriptors for the
[code]#device# class.
[source,,linenums]
----
include::{header_dir}/deviceInfo.h[lines=4..-1]
----


[[appendix.queue.descriptors]]
== Queue information descriptors

The following interface includes all the information descriptors for the
[code]#queue# class.
[source,,linenums]
----
include::{header_dir}/queueInfo.h[lines=4..-1]
----


[[appendix.kernel.descriptors]]
== Kernel information descriptors

The following interface includes all the information descriptors that apply to
kernels as described in <<table.kernel.info>> and in
<<table.kernel.devicespecificinfo>>.
[source,,linenums]
----
include::{header_dir}/kernelInfo.h[lines=4..-1]
----


[[appendix.event.descriptors]]
== Event information descriptors

The following interface includes all the information descriptors for the
[code]#event# class as described in <<table.event.info>> and
<<table.event.profilinginfo>>.
[source,,linenums]
----
include::{header_dir}/eventInfo.h[lines=4..-1]
----


// %%%%%%%%%%%%%%%%%%%%%%%%%%%% end descriptors %%%%%%%%%%%%%%%%%%%%%%%%%%%%
