// %%%%%%%%%%%%%%%%%%%%%%%%%%%% begin introduction %%%%%%%%%%%%%%%%%%%%%%%%%%%%

[[introduction]]
= Introduction

// What is SYCL?
SYCL (pronounced "`sickle`") is a royalty-free, cross-platform API for
heterogeneous computing in {cpp}.

SYCL enables developers to write standard {cpp} code that executes on a wide
range of devices, using modern techniques such as inheritance, templates, and
lambda expressions.
All computational kernels to be executed on a device can be written inside {cpp}
source files as normal {cpp} code, alongside any code intended to be run on a
system's host processor.
This concept, known as "`single-source`" programming, reduces the complexity of
heterogeneous programming for developers and gives compilers greater
opportunities to analyze/optimize across the host-device boundary.

// How does SYCL relate to C++?
SYCL is designed to be as close to standard {cpp} as possible, and some
implementations of SYCL may be able to use a standard {cpp} compiler to target
CPU devices.
However, to ensure portability of device code across a wide range of devices,
SYCL imposes some restrictions on the set of {cpp} features that SYCL
implementations are required to support within device code.
These restrictions may not be applicable to all devices and can therefore be
relaxed by specific Khronos extensions or vendor extensions.

// How does SYCL relate to lower-level APIs?
SYCL was originally based on OpenCL, and retains an execution model, runtime
feature set, and device capability set inspired by the OpenCL standard.
However, there is no requirement that SYCL implementations must use OpenCL; SYCL
implementations are free to support devices via any low-level API (or
"`backend`") they choose.

// What are some key features of SYCL?
Some of the key features of SYCL are:

  * Common parallel patterns, such as <<sec:reduction, reductions>> and
    <<sec:algorithms, group algorithms>>, are exposed via high-level
    abstractions.

  * Interoperability with the lower-level capabilities of specific
    <<sec:backends, backends>> guarantees access to platform-specific
    optimizations.

  * <<subsec:buffers, Buffers>> and <<subsec:accessors, accessors>> provide a
    simple way to build task-graphs without manually managing dependencies.

  * <<sec:usm, Unified Shared Memory>> (USM) provides an explicit,
    pointer-based, mechanism for managing and sharing data.

// How would you summarize SYCL?
SYCL has been designed to enable implementations on a wide variety of platforms,
permitting easy integration with other platform-specific technologies.
Both users and implementers are encouraged to build upon SYCL as an open
platform for system-wide heterogeneous programming.


[[sec:normativerefs]]
== Normative references

Normative references are references to external documents or resources to which
implementers of SYCL must comply with all, or specified portions of, as
described in this specification.

International Organization for Standardization (ISO). +
ISO/IEC 14882:2017 - Programming languages - {cpp},
https://www.iso.org/standard/68564.html +
(Referred to as {cpp17} in this document.)

International Organization for Standardization (ISO). +
ISO/IEC 14882:2020 - Programming languages - {cpp},
https://www.iso.org/standard/79358.html +
(Referred to as {cpp20} in this document.)

International Organization for Standardization (ISO). +
ISO/IEC 14882:2024 - Programming languages - {cpp},
https://www.iso.org/standard/83626.html +
(Referred to as {cpp23} in this document.)

// Jon: are any of the OpenCL specifications normative? They are also
// referred to from the SYCL spec, and some of the definitions appear to be
// required.


[[sec:nonnormativerefs]]
== Non-normative notes and examples

Unless stated otherwise, text within this SYCL specification is normative and
defines the required behavior of a SYCL implementation.
Non-normative / informational notes are included within this specification using
either of two formats.
One format for non-normative notes is the "`note`" callout of this form:

[NOTE]
====
Information within a note callout, such as this text, is for informational
purposes and does not impose requirements on or specify behavior of a SYCL
implementation.
====

The other format for a non-normative note is like this:

{note}This is also a non-normative note.
{endnote}

Source code examples within the specification are provided to aid with
understanding, and are non-normative.

In case of any conflict between a non-normative note or source example, and
normative text within the specification, the normative text must be taken to be
correct.


[[sec:progmodel.minimumcppversion]]
== Minimum version of {cpp}

A SYCL implementation must conform to {cpp17} or to one of the more recent {cpp}
versions listed in <<sec:normativerefs>>.
The version of {cpp} to which a SYCL implementation conforms is referred to as
the {cpp} core language in this document.
All APIs in this specification are available regardless of the version of the
{cpp} core language unless the description specifically states otherwise.
If an API is documented with the phrase "Minimum C++ Version: __Version__", then
that API is available only if the version of the implementation's {cpp} core
language is at least _Version_.

{note}Not all {cpp} features are supported in SYCL <<device-function, device
functions>>.
See <<sec:language.restrictions.kernels>>.
{endnote}

{note}Applications should take care when using SYCL APIs or {cpp} features that
are not available in {cpp17}.
The use of such APIs or features may prevent an application from being portable
across all implementations of SYCL.
{endnote}

{note}Implementations may choose to make APIs documented as "Minimum C++
Version: __Version__" available even when the {cpp} version is less than
_Version_.
The recommended practice in this case is to use [code]#+__has_include+# and the
appropriate {cpp} feature-test macros to improve the portability of SYCL
applications across implementations.
{endnote}


[[sec::unified-spec]]
== Unified specification

This document provides the specification for both SYCL 2020 and SYCL
{SYCL_VERSION}.
It also provides the specification for extensions to the SYCL language in
<<chapter:extensions>>.
and the specification for the OpenCL backend in <<chapter:opencl-backend>>.
All APIs in these extensions and the backend specification may be used with any
of the SYCL versions specified in this document unless the description
specifically states otherwise.

If an API is documented as "Missing before SYCL __Version__", that API is newly
introduced in SYCL _Version_, so it is not available in versions of SYCL prior
to _Version_.

If an API is documented as "Deprecated by SYCL __Version__", that API is still
supported, but its use is discouraged in SYCL _Version_ and in subsequent
versions of SYCL.

If an API is documented as "Missing after SYCL __Version__", that API is removed
and no longer available in SYCL versions after _Version_.

// %%%%%%%%%%%%%%%%%%%%%%%%%%%% end introduction %%%%%%%%%%%%%%%%%%%%%%%%%%%%
